package my-org:my-workflow

interface host-activities {
    sleep: func(millis: u64)
}

world sleepy-workflow {
    import host-activities
    import component:wasm-email-provider/email-sender
    export execute: func() -> string
    export second: func() -> string
}
