package my-org:my-workflow

world sleepy-workflow {
    import my-org:workflow-engine/host-activities
    import my-org:wasm-email-provider/email-sender
    export execute: func() -> string
    export noop: func() -> string
}
