package testing:fibo-workflow;

interface workflow {
    fibow: func(n: u8, iterations: u32) -> u64;
    fiboa: func(n: u8, iterations: u32) -> u64;
    fiboa-concurrent: func(n: u8, iterations: u32) -> u64;
}

interface workflow-nesting {
    fibo-nested-workflow: func(n: u8) -> u64;
    fibo-start-fiboas: func(n: u8, fiboas: u32, iterations-per-fiboa: u32) -> u64;
}
