package testing:stub-activity-obelisk-ext;

interface activity {
    use obelisk:types/execution@2.0.0.{join-set-id, execution-error, execution-id, get-response-error};

    foo-submit: func(join-set-id: borrow<join-set-id>, arg: string) -> execution-id;
    foo-await-next: func(join-set-id: borrow<join-set-id>) -> result<tuple<execution-id, string>, tuple<execution-id, execution-error>>;

    // None if this execution is not marked as processed yet.
    // execution error can be ffqn mismatch
    // TODO foo-get: func(execution-id: execution-id) -> option<result<string, get-response-error>>;

    noret-submit: func(join-set-id: borrow<join-set-id>) -> execution-id;
    noret-await-next: func(join-set-id: borrow<join-set-id>) -> result<execution-id, tuple<execution-id, execution-error>>;
}
