[package]
name = "obelisk-activity-vm-worker"
description = "Internal Obelisk worker for Linux VM activities"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
activity-vm-runner.workspace = true
anyhow.workspace = true
async-trait.workspace = true
chrono.workspace = true
concepts.workspace = true
executor.workspace = true
secrecy.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
utils.workspace = true
wasm-workers.workspace = true
wasmtime.workspace = true
worker-common.workspace = true

[dev-dependencies]
val-json.workspace = true

[lints]
workspace = true
