package any:any;

world any {
    export testing:stub-workflow/workflow;
    import testing:stub-activity-obelisk-ext/activity;  // for submitting the execution
    import testing:stub-activity-obelisk-stub/activity; // for submitting the execution result
    import testing:stub-activity/activity;              // for direct call
    import obelisk:workflow/workflow-support@2.0.0;
    import obelisk:log/log@1.0.0;
}
