[package]
name = "obeli-sk-worker-common"
description = "Shared types for Obelisk workers"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
secrecy.workspace = true
serde.workspace = true

[lints]
workspace = true
