[[activity_wasm]]
name = "test_programs_fibo_activity"
location = "oci://docker.io/getobelisk/test_programs_fibo_activity:2026-09-08@sha256:7fe489c25bb2df2cafd7a20cf04708d53ece714f62557a29c9f98f568ad56618"
max_retries = 0

[[workflow_wasm]]
name = "test_programs_fibo_workflow"
location = "oci://docker.io/getobelisk/test_programs_fibo_workflow:2026-09-08@sha256:f7e6f63acd3c3dbe755f89feb9dc16147a7f0f92d35510c19a7cde50deec21c9"
exec.lock_expiry.seconds = 2
backtrace.sources = { ".../src/lib.rs" = "crates/testing/test-programs/fibo/workflow/src/lib.rs" }

[[webhook_endpoint_wasm]]
name = "test_programs_fibo_webhook"
location = "oci://docker.io/getobelisk/test_programs_fibo_webhook:2026-09-08@sha256:03881f362862d3b4ff386c7af0010374fda44652aee717061859d906bd99cae4"
routes = [{ methods = ["GET"], route = "/fibo/:N/:ITERATIONS" }]
backtrace.sources = { ".../src/lib.rs" = "crates/testing/test-programs/fibo/webhook/src/lib.rs" }

[[activity_wasm]]
name = "test_programs_http_get_activity"
location = "oci://docker.io/getobelisk/test_programs_http_get_activity:2026-09-08@sha256:29aa95f67babf62b659105cd59341da8dbc1518e4d0b82a0a7967743200fdce7"

[[workflow_wasm]]
name = "test_programs_http_get_workflow"
location = "oci://docker.io/getobelisk/test_programs_http_get_workflow:2026-09-08@sha256:3f68c8b4b96ff89e2c16df4f3fcb685bbe655ca403452cb8d880d180923c9066"
backtrace.sources = { ".../src/lib.rs" = "crates/testing/test-programs/http/workflow/src/lib.rs" }

[[activity_wasm]]
name = "test_programs_sleep_activity"
location = "oci://docker.io/getobelisk/test_programs_sleep_activity:2026-09-08@sha256:499ea2920c681b61b01c0f669d2ea0e1d47fa8482f0db4ae078a4547415ceca6"
exec.lock_expiry.seconds = 10

[[workflow_wasm]]
name = "test_programs_sleep_workflow"
location = "oci://docker.io/getobelisk/test_programs_sleep_workflow:2026-09-08@sha256:30c8a23c1d2c0936d74bcf04f32c3725a60ac351bb7fa0af461e917da654afc6"
backtrace.sources = { ".../src/lib.rs" = "crates/testing/test-programs/sleep/workflow/src/lib.rs" }
