[[activity_wasm]]
name = "test_programs_fibo_activity"
location = "${DEPLOYMENT_DIR}/target/release_testprograms/wasm32-wasip2/release_testprograms/test_programs_fibo_activity.wasm"
max_retries = 0

[[workflow_wasm]]
name = "test_programs_fibo_workflow"
location = "${DEPLOYMENT_DIR}/target/release_testprograms/wasm32-unknown-unknown/release_testprograms/test_programs_fibo_workflow.wasm"
exec.lock_expiry.seconds = 2
backtrace.sources = { ".../src/lib.rs" = "${DEPLOYMENT_DIR}/crates/testing/test-programs/fibo/workflow/src/lib.rs" }

[[workflow_wasm]]
name = "test_programs_fibo_workflow_outer"
location = "${DEPLOYMENT_DIR}/target/release_testprograms/wasm32-unknown-unknown/release_testprograms/test_programs_fibo_workflow_outer.wasm"
exec.lock_expiry.seconds = 2
backtrace.sources = { ".../src/lib.rs" = "${DEPLOYMENT_DIR}/crates/testing/test-programs/fibo/workflow-outer/src/lib.rs" }

[[webhook_endpoint_wasm]]
name = "test_programs_fibo_webhook"
location = "${DEPLOYMENT_DIR}/target/release_testprograms/wasm32-wasip2/release_testprograms/test_programs_fibo_webhook.wasm"
routes = [{ methods = ["GET"], route = "/fibo/:N/:ITERATIONS" }]
backtrace.sources = { ".../src/lib.rs" = "${DEPLOYMENT_DIR}/crates/testing/test-programs/fibo/webhook/src/lib.rs" }

[[activity_wasm]]
name = "test_programs_http_get_activity"
location = "${DEPLOYMENT_DIR}/target/release_testprograms/wasm32-wasip2/release_testprograms/test_programs_http_get_activity.wasm"
max_retries = 0
exec.lock_expiry.seconds = 5
[[activity_wasm.allowed_host]]
pattern = "*" # only https allowed
methods = "*"

[[activity_wasm.allowed_host]]
pattern = "httpbin.org"
methods = "*"
secrets = {env_vars = [{key = "API_KEY", value = "foo"}], replace_in = ["headers", "params", "body"] }

[[workflow_wasm]]
name = "test_programs_http_get_workflow"
location = "${DEPLOYMENT_DIR}/target/release_testprograms/wasm32-unknown-unknown/release_testprograms/test_programs_http_get_workflow.wasm"
backtrace.sources = { ".../src/lib.rs" = "${DEPLOYMENT_DIR}/crates/testing/test-programs/http/workflow/src/lib.rs" }

[[activity_wasm]]
name = "test_programs_sleep_activity"
location = "${DEPLOYMENT_DIR}/target/release_testprograms/wasm32-wasip2/release_testprograms/test_programs_sleep_activity.wasm"
exec.lock_expiry.seconds = 10

[[workflow_wasm]]
name = "test_programs_sleep_workflow"
location = "${DEPLOYMENT_DIR}/target/release_testprograms/wasm32-unknown-unknown/release_testprograms/test_programs_sleep_workflow.wasm"
backtrace.sources = { ".../src/lib.rs" = "${DEPLOYMENT_DIR}/crates/testing/test-programs/sleep/workflow/src/lib.rs" }

[[webhook_endpoint_wasm]]
name = "test_programs_sleep_webhook"
location = "${DEPLOYMENT_DIR}/target/release_testprograms/wasm32-wasip2/release_testprograms/test_programs_sleep_webhook.wasm"
routes = [{ methods = ["GET"], route = "/sleep/:SECONDS" }]
backtrace.sources = { ".../src/lib.rs" = "${DEPLOYMENT_DIR}/crates/testing/test-programs/sleep/webhook/src/lib.rs" }

[[activity_wasm]]
name = "test_programs_serde_activity"
location = "${DEPLOYMENT_DIR}/target/release_testprograms/wasm32-wasip2/release_testprograms/test_programs_serde_activity.wasm"
max_retries = 0

[[workflow_wasm]]
name = "test_programs_serde_workflow"
location = "${DEPLOYMENT_DIR}/target/release_testprograms/wasm32-unknown-unknown/release_testprograms/test_programs_serde_workflow.wasm"

[[activity_stub]]
name = "test_programs_stub_activity_dummy"
location = "${DEPLOYMENT_DIR}/target/release_testprograms/wasm32-wasip2/release_testprograms/test_programs_stub_activity.wasm"

[[workflow_wasm]]
name = "test_programs_stub_workflow"
location = "${DEPLOYMENT_DIR}/target/release_testprograms/wasm32-unknown-unknown/release_testprograms/test_programs_stub_workflow.wasm"
backtrace.sources = { ".../src/lib.rs" = "${DEPLOYMENT_DIR}/crates/testing/test-programs/stub/workflow/src/lib.rs" }
