[[activity_wasm]]
name = "test_programs_fibo_activity"
location = "oci://docker.io/getobelisk/test_programs_fibo_activity:2026-07-11-1@sha256:99428bbdfaff4a89039eb10ed76dac72b295da7cb1c52fbe849254049b90f8d6"
max_retries = 0

[[workflow_wasm]]
name = "test_programs_fibo_workflow"
location = "oci://docker.io/getobelisk/test_programs_fibo_workflow:2026-07-11-1@sha256:7185866a3485aae4f8ca51a8e4f56893e7f4b27bb57d9dcb6a972bb461539f02"
exec.lock_expiry.seconds = 2
backtrace.sources = { ".../src/lib.rs" = "crates/testing/test-programs/fibo/workflow/src/lib.rs" }

[[webhook_endpoint_wasm]]
name = "test_programs_fibo_webhook"
location = "oci://docker.io/getobelisk/test_programs_fibo_webhook:2026-07-11-1@sha256:3f4d9906de1af98653ca8d098d4d94cddc57ae40d75c34dc0a9953fa21766721"
routes = [{ methods = ["GET"], route = "/fibo/:N/:ITERATIONS" }]
backtrace.sources = { ".../src/lib.rs" = "crates/testing/test-programs/fibo/webhook/src/lib.rs" }

[[activity_wasm]]
name = "test_programs_http_get_activity"
location = "oci://docker.io/getobelisk/test_programs_http_get_activity:2026-07-11-1@sha256:a28ab69ccc2daea4da6581283efe7802f152bc565eb164f32c25b80cd1d3201e"

[[workflow_wasm]]
name = "test_programs_http_get_workflow"
location = "oci://docker.io/getobelisk/test_programs_http_get_workflow:2026-07-11-1@sha256:5f8e762007e9a9450cd28e2c4d5543d9f7c9c33daf93087ba947b96afd281e52"
backtrace.sources = { ".../src/lib.rs" = "crates/testing/test-programs/http/workflow/src/lib.rs" }

[[activity_wasm]]
name = "test_programs_sleep_activity"
location = "oci://docker.io/getobelisk/test_programs_sleep_activity:2026-07-11-1@sha256:a8fbf4416d096e5bfe0ce79710408fe53ee0407f5e384dae2f6b9f0f9f33f77e"
exec.lock_expiry.seconds = 10

[[workflow_wasm]]
name = "test_programs_sleep_workflow"
location = "oci://docker.io/getobelisk/test_programs_sleep_workflow:2026-07-11-1@sha256:9c6be9dc56172358750c5df991d6f7e71088b2dd90d4c49d8d689a45508ca5e9"
backtrace.sources = { ".../src/lib.rs" = "crates/testing/test-programs/sleep/workflow/src/lib.rs" }
