api.listening_addr = "127.0.0.1:5005"
webui.listening_addr = "127.0.0.1:8080"

database.postgres.host =     "${POSTGRES_HOST}"
database.postgres.user =     "${POSTGRES_USER}"
database.postgres.password = "${POSTGRES_PASSWORD}"
database.postgres.db_name =  "${POSTGRES_DATABASE}"
database.postgres.provision_policy = "auto"

[log.file]
enabled = true
target = true
directory = "."
prefix = "obelisk.log"

[[http_server]]
name = "external_webhook"
listening_addr = "127.0.0.1:9090"

[[activity_wasm]]
name = "test_programs_fibo_activity"
location = "oci://docker.io/getobelisk/test_programs_fibo_activity:2026-02-23@sha256:eff1dd0a9c852ed026f592ac205b370396f87a5f720bbbb0d186315e236598c8"
max_retries = 0

[[workflow]]
name = "test_programs_fibo_workflow"
location = "oci://docker.io/getobelisk/test_programs_fibo_workflow:2026-02-23@sha256:bbaae15ff680a7b9e524d583561e2e643e8d0834adc91eeefcef2baca3bd7dcd"
exec.lock_expiry.seconds = 2
backtrace.sources = { ".../src/lib.rs" = "${OBELISK_TOML_DIR}/crates/testing/test-programs/fibo/workflow/src/lib.rs" }

[[webhook_endpoint]]
name = "test_programs_fibo_webhook"
location = "oci://docker.io/getobelisk/test_programs_fibo_webhook:2026-02-23@sha256:eb2f227dd3700b87922751d965a8d7d6da36052956f85824d7285f4aa99a9d5b"
http_server = "external_webhook"
routes = [{ methods = ["GET"], route = "/fibo/:N/:ITERATIONS" }]
backtrace.sources = { ".../src/lib.rs" = "${OBELISK_TOML_DIR}/crates/testing/test-programs/fibo/webhook/src/lib.rs" }

[[activity_wasm]]
name = "test_programs_http_get_activity"
location = "oci://docker.io/getobelisk/test_programs_http_get_activity:2026-02-23@sha256:e077ff941cebd2a4127196b7e4278e15b68216d2ea33f278cbb07dbbd2f105d7"

[[workflow]]
name = "test_programs_http_get_workflow"
location = "oci://docker.io/getobelisk/test_programs_http_get_workflow:2026-02-23@sha256:37c722f14e2112b173b46b9758cd66904a92d468cee25b0a093b17229bcbc2b9"
backtrace.sources = { ".../src/lib.rs" = "${OBELISK_TOML_DIR}/crates/testing/test-programs/http/workflow/src/lib.rs" }

[[activity_wasm]]
name = "test_programs_sleep_activity"
location = "oci://docker.io/getobelisk/test_programs_sleep_activity:2026-02-23@sha256:8137a350d96bfe685d1f979e3b30f1afda354f6ac2bb985ed3d343d59916e229"
exec.lock_expiry.seconds = 10

[[workflow]]
name = "test_programs_sleep_workflow"
location = "oci://docker.io/getobelisk/test_programs_sleep_workflow:2026-02-23@sha256:f89e2b60083b6920c44c721d9ef35b8c983d2e56a18b26272bf74931986b25f6"
backtrace.sources = { ".../src/lib.rs" = "${OBELISK_TOML_DIR}/crates/testing/test-programs/sleep/workflow/src/lib.rs" }
