[[activity_wasm]]
name = "test_programs_fibo_activity"
location = "oci://docker.io/getobelisk/test_programs_fibo_activity:2026-04-06@sha256:d6cbc0494da6ba9ecde738b5bca437f543860e6e8cb3c0a6413ce612c4affc68"
max_retries = 0

[[workflow_wasm]]
name = "test_programs_fibo_workflow"
location = "oci://docker.io/getobelisk/test_programs_fibo_workflow:2026-04-06@sha256:c232a058f391459e925a571e719ab25faf80759c75c08a5df666ee6870ca8838"
exec.lock_expiry.seconds = 2
backtrace.sources = { ".../src/lib.rs" = "${DEPLOYMENT_DIR}/crates/testing/test-programs/fibo/workflow/src/lib.rs" }

[[webhook_endpoint_wasm]]
name = "test_programs_fibo_webhook"
location = "oci://docker.io/getobelisk/test_programs_fibo_webhook:2026-04-06@sha256:be962a066f58b11f4bb506a4038282586a9961f729170265101248fc4e76cfa5"
routes = [{ methods = ["GET"], route = "/fibo/:N/:ITERATIONS" }]
backtrace.sources = { ".../src/lib.rs" = "${DEPLOYMENT_DIR}/crates/testing/test-programs/fibo/webhook/src/lib.rs" }

[[activity_wasm]]
name = "test_programs_http_get_activity"
location = "oci://docker.io/getobelisk/test_programs_http_get_activity:2026-04-06@sha256:d6bedd73d366c7b92b0a19896fa0bac7f67e6d2412ad5af1167be46edab24dd2"

[[workflow_wasm]]
name = "test_programs_http_get_workflow"
location = "oci://docker.io/getobelisk/test_programs_http_get_workflow:2026-04-06@sha256:82a7668efac561f342ea4bc4e64131591f66c71078e17cc85657879c88df06e6"
backtrace.sources = { ".../src/lib.rs" = "${DEPLOYMENT_DIR}/crates/testing/test-programs/http/workflow/src/lib.rs" }

[[activity_wasm]]
name = "test_programs_sleep_activity"
location = "oci://docker.io/getobelisk/test_programs_sleep_activity:2026-04-06@sha256:ec3e90b43243f1b75df13e668011bb769dc63880b8317fcba2a1f31fae347e39"
exec.lock_expiry.seconds = 10

[[workflow_wasm]]
name = "test_programs_sleep_workflow"
location = "oci://docker.io/getobelisk/test_programs_sleep_workflow:2026-04-06@sha256:41b2a3433ecbb5d03ec45cf9ed7c427db1d6293dcc22ee9b67cc39488b836830"
backtrace.sources = { ".../src/lib.rs" = "${DEPLOYMENT_DIR}/crates/testing/test-programs/sleep/workflow/src/lib.rs" }
