api.listening_addr = "127.0.0.1:5005"   # Address and port on which the API server will listen.
webui.listening_addr = "127.0.0.1:8080" # Address and port on which the webui will listen.
log.stdout.enabled = true
activities.directories.enabled = true

[[http_server]]
name = "external_webhook"
listening_addr = "127.0.0.1:9090"

[[activity_wasm]]
name = "test_programs_fibo_activity"
location.path = "target/release_testprograms/wasm32-wasip2/release/test_programs_fibo_activity.wasm"
max_retries = 0

[[workflow]]
name = "test_programs_fibo_workflow"
location.path = "target/release_testprograms/wasm32-unknown-unknown/release/test_programs_fibo_workflow.wasm"
exec.lock_expiry.seconds = 2
backtrace.sources = { "${OBELISK_TOML_DIR}/crates/testing/test-programs/fibo/workflow/src/lib.rs" = "${OBELISK_TOML_DIR}/crates/testing/test-programs/fibo/workflow/src/lib.rs" }

[[webhook_endpoint]]
name = "test_programs_fibo_webhook"
location.path = "target/release_testprograms/wasm32-wasip2/release/test_programs_fibo_webhook.wasm"
http_server = "external_webhook"
routes = [{ methods = ["GET"], route = "/fibo/:N/:ITERATIONS" }]
backtrace.sources = { "${OBELISK_TOML_DIR}/crates/testing/test-programs/fibo/webhook/src/lib.rs" = "${OBELISK_TOML_DIR}/crates/testing/test-programs/fibo/webhook/src/lib.rs" }

[[activity_wasm]]
name = "test_programs_http_get_activity"
location.path = "target/release_testprograms/wasm32-wasip2/release/test_programs_http_get_activity.wasm"
forward_stdout = "stderr"
forward_stderr = "stderr"

[[workflow]]
name = "test_programs_http_get_workflow"
location.path = "target/release_testprograms/wasm32-unknown-unknown/release/test_programs_http_get_workflow.wasm"
backtrace.sources = { "${OBELISK_TOML_DIR}/crates/testing/test-programs/http/workflow/src/lib.rs" = "${OBELISK_TOML_DIR}/crates/testing/test-programs/http/workflow/src/lib.rs" }

[[activity_wasm]]
name = "test_programs_sleep_activity"
location.path = "target/release_testprograms/wasm32-wasip2/release/test_programs_sleep_activity.wasm"
exec.lock_expiry.seconds = 10

[[workflow]]
name = "test_programs_sleep_workflow"
location.path = "target/release_testprograms/wasm32-unknown-unknown/release/test_programs_sleep_workflow.wasm"
backtrace.sources = { "${OBELISK_TOML_DIR}/crates/testing/test-programs/sleep/workflow/src/lib.rs" = "${OBELISK_TOML_DIR}/crates/testing/test-programs/sleep/workflow/src/lib.rs" }

[[activity_wasm]]
name = "test_programs_dir_activity"
location.path = "target/release_testprograms/wasm32-wasip2/release/test_programs_dir_activity.wasm"
max_retries = 1
forward_stdout = "stderr"
forward_stderr = "stderr"
directories = { enabled = true, reuse_on_retry = true }

[[activity_wasm]]
name = "test_programs_process_activity"
location.path = "target/release_testprograms/wasm32-wasip2/release/test_programs_process_activity.wasm"
max_retries = 0
forward_stdout = "stderr"
forward_stderr = "stderr"
directories = { enabled = true, reuse_on_retry = false, process_provider = "native" }
env_vars = ["PATH"]                                                                                     # Needed for spawning subprocesses.

[[activity_wasm]]
name = "test_programs_serde_activity"
location.path = "target/release_testprograms/wasm32-wasip2/release/test_programs_serde_activity.wasm"
max_retries = 0
forward_stdout = "stderr"
forward_stderr = "stderr"

[[activity_wasm]] # TODO: activity_stub
name = "test_programs_stub_activity_dummy"
location.path = "target/release_testprograms/wasm32-wasip2/release/test_programs_stub_activity.wasm"
stub = true

# [[workflow]]
# name = "test_programs_stub_workflow"
# location.path = "target/release_testprograms/wasm32-unknown-unknown/release/test_programs_stub_workflow.wasm"
