[[activity_wasm]]
name = "test_programs_fibo_activity"
location = "oci://docker.io/getobelisk/test_programs_fibo_activity:2026-07-10@sha256:e18428c374d96ff2f0839cb179b5cb6895ab65bdd52b8a9c7868f366252f6320"
max_retries = 0

[[workflow_wasm]]
name = "test_programs_fibo_workflow"
location = "oci://docker.io/getobelisk/test_programs_fibo_workflow:2026-07-10@sha256:5a78d91161cb3d9e41d6ceae41de27fe189d445e16ab4a3668bb4789c7245ed7"
exec.lock_expiry.seconds = 2
backtrace.sources = { ".../src/lib.rs" = "crates/testing/test-programs/fibo/workflow/src/lib.rs" }

[[webhook_endpoint_wasm]]
name = "test_programs_fibo_webhook"
location = "oci://docker.io/getobelisk/test_programs_fibo_webhook:2026-07-10@sha256:cdb600b827530802946b53903e13f4ddd106caa3d36bf22c6aa2d44ff3c168fc"
routes = [{ methods = ["GET"], route = "/fibo/:N/:ITERATIONS" }]
backtrace.sources = { ".../src/lib.rs" = "crates/testing/test-programs/fibo/webhook/src/lib.rs" }

[[activity_wasm]]
name = "test_programs_http_get_activity"
location = "oci://docker.io/getobelisk/test_programs_http_get_activity:2026-07-10@sha256:c4cf535bd2b55e10810b0002a326896fc9351fc38780c239a3358bfc773bb4d7"

[[workflow_wasm]]
name = "test_programs_http_get_workflow"
location = "oci://docker.io/getobelisk/test_programs_http_get_workflow:2026-07-10@sha256:09697cbc069f33fa226ba4c3731794ac244d9bf4a6b5cb27e51326e84a9d88bc"
backtrace.sources = { ".../src/lib.rs" = "crates/testing/test-programs/http/workflow/src/lib.rs" }

[[activity_wasm]]
name = "test_programs_sleep_activity"
location = "oci://docker.io/getobelisk/test_programs_sleep_activity:2026-07-10@sha256:17ff0c46bb3716bd406f8748348bd460011b15a005bf93649de7deae913ba6d6"
exec.lock_expiry.seconds = 10

[[workflow_wasm]]
name = "test_programs_sleep_workflow"
location = "oci://docker.io/getobelisk/test_programs_sleep_workflow:2026-07-10@sha256:7ec3ca4afd05352b7884d3b85fd58827a91898f1fdd0ba05b06328976ce2e426"
backtrace.sources = { ".../src/lib.rs" = "crates/testing/test-programs/sleep/workflow/src/lib.rs" }
