[[activity_exec]]
ffqn = "testing:integration/exec-stream.stream-test"
content = '''#!/usr/bin/env bash
set -exuo pipefail

echo "line1" >&2
sleep 0.1
echo "line2" >&2
'''
env_vars = ["PATH"] # for sleep

[[activity_exec]]
ffqn = "testing:integration/exec-greet.greet-include"
location = "${DEPLOYMENT_DIR}/crates/testing/test-programs/exec/greet.sh"
params = [
  { name = "name", type = "string" },
]
return_type = "result<string, string>"
env_vars = ["PATH"] # for jq

[[activity_exec]]
ffqn = "testing:integration/exec-greet.greet-inline"
content = '''
#!/usr/bin/env bash
set -exuo pipefail
raw=$(echo $1 | jq -r .)
echo "\"Hello, $raw!\""
'''
params = [
  { name = "name", type = "string" },
]
return_type = "result<string, string>"
env_vars = ["PATH"] # for jq


[[activity_exec]]
ffqn = "testing:integration/exec-busy.busy"
content = '''
#!/usr/bin/env bash
i=0
while true; do
    if (( i % 1000000 == 0 )); then
        echo "$i"
    fi
    ((i++))
done
'''
exec.lock_expiry.seconds = 10
