api.listening_addr = "127.0.0.1:5005"
webui.listening_addr = "127.0.0.1:8080"

database.postgres.host =     "${POSTGRES_HOST}"
database.postgres.user =     "${POSTGRES_USER}"
database.postgres.password = "${POSTGRES_PASSWORD}"
database.postgres.db_name =  "${POSTGRES_DATABASE}"
database.postgres.provision_policy = "auto"

[log.file]
enabled = true
target = true
directory = "."
prefix = "obelisk.log"

[[http_server]]
name = "external_webhook"
listening_addr = "127.0.0.1:9090"

[[activity_wasm]]
name = "test_programs_fibo_activity"
location = "oci://docker.io/getobelisk/test_programs_fibo_activity:2026-02-24@sha256:0b82c934d0fb491dd7323481ece0d9a632b244838aa5ac5b386d68de35f6961c"
max_retries = 0

[[workflow]]
name = "test_programs_fibo_workflow"
location = "oci://docker.io/getobelisk/test_programs_fibo_workflow:2026-02-24@sha256:3b94250cd1b1188c7e656a0c7d33244e65e4c185704b0763ea021c949cb48cce"
exec.lock_expiry.seconds = 2
backtrace.sources = { ".../src/lib.rs" = "${OBELISK_TOML_DIR}/crates/testing/test-programs/fibo/workflow/src/lib.rs" }

[[webhook_endpoint]]
name = "test_programs_fibo_webhook"
location = "oci://docker.io/getobelisk/test_programs_fibo_webhook:2026-02-24@sha256:e018e938470e6a5883f7ffe6c475e38c081b310d7cc69b00d8773094de306b62"
http_server = "external_webhook"
routes = [{ methods = ["GET"], route = "/fibo/:N/:ITERATIONS" }]
backtrace.sources = { ".../src/lib.rs" = "${OBELISK_TOML_DIR}/crates/testing/test-programs/fibo/webhook/src/lib.rs" }

[[activity_wasm]]
name = "test_programs_http_get_activity"
location = "oci://docker.io/getobelisk/test_programs_http_get_activity:2026-02-24@sha256:a6cc57afe046d67359d8b5daabafa391b911632664eeab0f26d67bb00275dc54"

[[workflow]]
name = "test_programs_http_get_workflow"
location = "oci://docker.io/getobelisk/test_programs_http_get_workflow:2026-02-24@sha256:f2cabc137e7f758e6f33ddcdba8fcdc75c76a216b578f67a19a0f5eb6ce921d7"
backtrace.sources = { ".../src/lib.rs" = "${OBELISK_TOML_DIR}/crates/testing/test-programs/http/workflow/src/lib.rs" }

[[activity_wasm]]
name = "test_programs_sleep_activity"
location = "oci://docker.io/getobelisk/test_programs_sleep_activity:2026-02-24@sha256:38a6a1d69c5688a0dce419fac49123c766e581a151bfe7ea7abcf2829db9255c"
exec.lock_expiry.seconds = 10

[[workflow]]
name = "test_programs_sleep_workflow"
location = "oci://docker.io/getobelisk/test_programs_sleep_workflow:2026-02-24@sha256:a95ade5c0f8c4e602dbe1aed4e47243ad68f4f268cd07dad02b4249bce60727f"
backtrace.sources = { ".../src/lib.rs" = "${OBELISK_TOML_DIR}/crates/testing/test-programs/sleep/workflow/src/lib.rs" }
