[[activity_js]]
name = "test_add_activity"
location = "${DEPLOYMENT_DIR}/crates/testing/test-programs/js/activity/add.js"
ffqn = "testing:integration/activity.add"
params = [
  { name = "a", type = "u32" },
  { name = "b", type = "u32" },
]
max_retries = 0

[[workflow_js]]
name = "test_add_via_activity_workflow"
location = "${DEPLOYMENT_DIR}/crates/testing/test-programs/js/workflow/add_via_activity.js"
ffqn = "testing:integration/workflow-add-via-activity.add-via-activity"
params = [
  { name = "a", type = "u32" },
  { name = "b", type = "u32" },
]

[[activity_js]]
name = "test_read_env_activity"
location = "${DEPLOYMENT_DIR}/crates/testing/test-programs/js/activity/read_env.js"
ffqn = "testing:integration/activity.read-env"
params = [
  { name = "key", type = "string" },
]
max_retries = 0
env_vars = [{key = "TEST_ENV_VAR", value = "hello_from_env"}]

[[activity_js]]
name = "activity_js_fetch_get"
location = "${DEPLOYMENT_DIR}/crates/testing/test-programs/js/activity/fetch_get.js"
ffqn = "testing:js/activity.fetch-get"
params = [
    {name = "url", type = "string"},
    {name = "headers", type = "list<tuple<string,string>>"},
]
return_type = "result<string, string>"
max_retries = 0
[[activity_js.allowed_host]]
pattern = "http://localhost:5005"
methods = ["GET"]

[[workflow_js]]
name = "workflow_js_test"
location = "${DEPLOYMENT_DIR}/crates/testing/test-programs/js/workflow/fetch_components.js"
ffqn = "testing:js/workflow.fetch-components"
params = []

[[workflow_js]]
name = "test_call_activity_workflow"
location = "${DEPLOYMENT_DIR}/crates/testing/test-programs/js/workflow/call_activity.js"
ffqn = "testing:integration/workflow-call-activity.call-activity"
params = [
  { name = "a", type = "u32" },
  { name = "b", type = "u32" },
]

[[webhook_endpoint_js]]
name = "webhook_js_hello"
location = "${DEPLOYMENT_DIR}/crates/testing/test-programs/js/webhook/hello.js"
routes = [{ methods = ["GET"], route = "/hello" }]

[[webhook_endpoint_js]]
name = "webhook_js_fetch_components"
location = "${DEPLOYMENT_DIR}/crates/testing/test-programs/js/webhook/fetch_components.js"
routes = [{ methods = ["GET"], route = "/fetch" }]
[[webhook_endpoint_js.allowed_host]]
pattern = "http://localhost:5005"
methods = ["GET"]

[[webhook_endpoint_js]]
name = "webhook_js_call_activity"
location = "${DEPLOYMENT_DIR}/crates/testing/test-programs/js/webhook/call_activity.js"
routes = [{ methods = ["GET"], route = "/call-activity/:a/:b" }]

# stub

[[workflow_js]]
name = "test_call_stub_workflow"
location = "${DEPLOYMENT_DIR}/crates/testing/test-programs/js/workflow/call_stub.js"
ffqn = "testing:integration/workflow-call-stub.call-stub"
params = [
  { name = "id", type = "u64" },
]
return_type = "result<string, string>"

[[activity_stub]]
name = "test_inline_stub"
ffqn = "testing:integration/stubs.my-stub"
params = [
  { name = "id", type = "u64" },
]
return_type = "result<string, string>"

# Busy workflow

[[workflow_js]]
name = "workflow_busy_sleep"
location = "${DEPLOYMENT_DIR}/crates/testing/test-programs/js/workflow/busy-sleep.js"
ffqn = "testing:integration/workflow-busy.busy"
params = []
return_type = "result<string, string>"

[[activity_js]]
name = "activity_busy_sleep"
location = "${DEPLOYMENT_DIR}/crates/testing/test-programs/js/activity/sleep.js"
ffqn = "testing:integration/sleep-activity.sleep"
params = [
  { name = "milliseconds", type = "u64" },
]
return_type = "result"
max_retries = 0

[[workflow_js]]
name = "workflow_busy_cpu"
location = "${DEPLOYMENT_DIR}/crates/testing/test-programs/js/workflow/busy-cpu.js"
ffqn = "testing:integration/workflow-busy-cpu.busy-cpu"
params = []
exec.lock_expiry.seconds = 10

[[activity_js]]
name = "activity_busy_cpu"
location = "${DEPLOYMENT_DIR}/crates/testing/test-programs/js/activity/busy-cpu.js"
ffqn = "testing:integration/activity-busy-cpu.busy-cpu"
params = []
exec.lock_expiry.seconds = 10
