[[outbound_http.allowed_host]]
pattern = "*"
methods = "*"

[[outbound_http.allowed_host]]
pattern = "httpbin.org"
methods = "*"
secrets = ["MY_SECRET"]
replace_in = ["headers", "params", "body"]

[secrets]
MY_SECRET = { env = "MY_SECRET" }

[database.postgres]
host =     "${POSTGRES_HOST}"
user =     "${POSTGRES_USER}"
password = "${POSTGRES_PASSWORD}"
db_name =  "${POSTGRES_DATABASE}"
provision_policy = "auto"
