package testing:http-workflow;

interface workflow {
    get: func(url: string) -> result<string, string>;
    get-resp: func(url: string) -> result<string, string>;
    get-successful: func(url: string) -> result<string, string>;
    get-successful-concurrently: func(urls: list<string>) -> result<list<string>, string>;
    get-successful-concurrently-stress: func(url: string, concurrency: u32) -> result<list<string>, string>;

}
