package any:any;

world any {
    export testing:sleep-workflow/workflow;
    import obelisk:workflow/host-activities;
    import testing:sleep-obelisk-ext/sleep;
    import testing:sleep-workflow-obelisk-ext/workflow;
    import testing:sleep/sleep;
}
