package any:any;

world any {
    export testing:sleep-workflow/workflow;
    import obelisk:workflow/workflow-support@4.2.0;

    import testing:sleep/sleep;
    import testing:sleep-obelisk-ext/sleep;
    import testing:sleep-obelisk-schedule/sleep;
    import obelisk:log/log@1.0.0;
}
