package testing:sleep-workflow;

interface workflow {
    sleep-host-activity: func(millis: u32);
    sleep-activity: func(millis: u32);
    run: func();
}

world any {
    import my-org:workflow-engine/host-activities;
    import testing:sleep/sleep;
    import wasi:cli/run@0.2.0;
    export workflow;
}
