package obelisk:workflow@1.0.0;

interface workflow-support {
    use obelisk:types/time@1.0.0.{duration};
    use obelisk:types/execution@1.0.0.{join-set-id};

    /// Persistent sleep.
    sleep: func(duration: duration);
    // TODO: sleep-submit

    /// Create new join set. Closing the join set at the execution finish will block until all child executions are finished.
    join-set: func(name: string) -> join-set-id;

    // TODO: `join-set-cancelling(name: string)` that cancels all remaining child executions on close
}
