[package]
name = "test-programs-http-get-workflow"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
wit-bindgen-rt.workspace = true

[lib]
crate-type = ["cdylib"]

[package.metadata.component.dependencies]

[package.metadata.component.target.dependencies]
"testing:http" = { path = "../activity/wit/ifc" }
"testing:http-obelisk-ext" = { path = "../activity//wit/ext" }
"obelisk:workflow".path = "../../../../wasm-workers/host-wit/"
"wasi:clocks".path = "../../../../wasm-workers/host-wit/deps/clocks"

[lints]
clippy.unnecessary_cast = "allow"
clippy.wrong_self_convention = "allow"
rust.unused_braces = "allow"
rust.unused_imports = "allow"
