package obelisk:workflow;

interface host-activities {
    use wasi:clocks/wall-clock@0.2.0.{datetime};

    sleep: func(millis: u32);
    new-join-set: func() -> string;

    /// A duration of time, in nanoseconds.
    type duration = u64;


    variant scheduled-at {
        now,
        at(datetime),
        in(duration),
    }

    schedule: func(ffqn: string, params-json: string, scheduled-at: scheduled-at) -> string;
}
