[package]
name = "test-programs-serde-workflow-builder"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[build-dependencies]
obelisk-component-builder.workspace = true
