package testing:noop-workflow;

interface workflow {
    noopa: func(iterations: u32);
    noopha: func(iterations: u32);
    noopw: func(iterations: u32);
}

world any {
    import testing:noop/noop;
    import my-org:workflow-engine/host-activities;
    export workflow;
}
