package obelisk:types@2.0.0;

interface time {

    variant duration {
        milliseconds(u64),
        seconds(u64),
        minutes(u32),
        hours(u32),
        days(u32),
    }

    /// A time and date in seconds plus nanoseconds.
    // Extracted from wasi:clocks@0.2.0 to avoid dependency on wasi:io
    record datetime {
        seconds: u64,
        nanoseconds: u32,
    }

    variant schedule-at {
        now,
        at(datetime),
        in(duration),
    }
}

interface execution {
    resource join-set-id {
        id: func() -> string;
        // TODO: sleep-submit
        // TODO: await-next
    }
    record execution-id {
        id: string,
    }

    record delay-id {
        id: string,
    }

    record execution-failed {
        execution-id: execution-id,
    }

    record function {
        // `namespace:pkg_name/ifc_name` or `namespace:pkg_name/ifc_name@version`
        interface-name: string,
        function-name: string,
    }

    variant response-id {
        execution-id(execution-id),
        delay-id(delay-id),
    }

    record function-mismatch {
        /// Workflow requested function
        specified-function: function,
        /// What was found actually during execution. None if delay was found as next unprocessed response.
        actual-function: option<function>,
        actual-id: response-id,
    }

    /// Error that is thrown by `-await-next` extension functions.
    variant execution-error {
        /// Execution response was awaited and marked as processed, but it finished with an error.
        execution-failed(execution-failed),
        /// All submitted requests and their responses of specified function and join set were already processed.
        all-processed,
        /// Execution response was awaited and marked as processed, but it belongs to a different function.
        /// This can happen when join set contains responses of multiple functions or delay requests.
        function-mismatch(function-mismatch),
    }

    /// Error that is thrown by `-get` extension functions.
    variant get-extension-error {
        /// Execution is found in processed responses, but it finished with an error.
        execution-failed(execution-failed),
        /// Execution is found in processed responses, but it belongs to a different function.
        /// This can happen when join set contains responses of multiple functions.
        function-mismatch(function-mismatch),
        /// Processed responses do not contain the specified execution ID.
        /// This can happen if the execution was not marked as processed (awaited), or
        /// the execution ID does not belong to the specified join set.
        not-found-in-processed-responses,
    }

    variant stub-error {
        /// Conflict can happen when a second writer attempts to stub a value, while the
        /// value is not equal to the already stubbed value.
        conflict,
    }
}
