package testing:stub-workflow;

interface workflow {
    use obelisk:types/execution@4.0.0.{execution-id};

    submit-stub-await: func(arg: string) -> result<string>;
    submit-await: func(arg: string) -> result<string>;

    noret-submit-await: func() -> result;

    submit-race-join-next-stub: func() -> result;
    submit-race-join-next-stub-error: func() -> result;
    submit-race-join-next-delay: func() -> result;

    stub-subworkflow: func(execution-id: execution-id, retval: string) -> result;

    await-next-produces-all-processed-error: func() -> result;

    join-next-in-scope: func() -> result;

    invoke-expect-execution-error: func() -> result;
}
