package testing:stub-workflow;

interface workflow {
    use obelisk:types/execution@2.0.0.{execution-id, stub-error};

    submit-stub-await: func(arg: string) -> string;
    submit-await: func(arg: string) -> string;

    noret-submit-await: func();

    submit-race-join-next-stub: func();
    submit-race-join-next-stub-error: func();
    submit-race-join-next-delay: func();

    stub-subworkflow: func(execution-id: execution-id, retval: string) -> result<_, stub-error>;

    await-next-produces-all-processed-error: func();

    join-next-in-scope: func();

    invoke-expect-execution-error: func();
}
