// Generated by `wit-bindgen` 0.21.0. DO NOT EDIT!
// Options used:
pub mod my_org {
    pub mod workflow_engine {
        #[allow(clippy::all)]
        pub mod host_activities {
            #[used]
            #[doc(hidden)]
            #[cfg(target_arch = "wasm32")]
            static __FORCE_SECTION_REF: fn() =
                super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[allow(unused_unsafe, clippy::all)]
            pub fn sleep(millis: u64) {
                unsafe {
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "my-org:workflow-engine/host-activities")]
                    extern "C" {
                        #[link_name = "sleep"]
                        fn wit_import(_: i64);
                    }

                    #[cfg(not(target_arch = "wasm32"))]
                    fn wit_import(_: i64) {
                        unreachable!()
                    }
                    wit_import(_rt::as_i64(&millis));
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn noop() {
                unsafe {
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "my-org:workflow-engine/host-activities")]
                    extern "C" {
                        #[link_name = "noop"]
                        fn wit_import();
                    }

                    #[cfg(not(target_arch = "wasm32"))]
                    fn wit_import() {
                        unreachable!()
                    }
                    wit_import();
                }
            }
        }
    }
}
pub mod testing {
    pub mod noop {
        #[allow(clippy::all)]
        pub mod noop {
            #[used]
            #[doc(hidden)]
            #[cfg(target_arch = "wasm32")]
            static __FORCE_SECTION_REF: fn() =
                super::super::super::__link_custom_section_describing_imports;
            #[allow(unused_unsafe, clippy::all)]
            pub fn noop() {
                unsafe {
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "testing:noop/noop")]
                    extern "C" {
                        #[link_name = "noop"]
                        fn wit_import();
                    }

                    #[cfg(not(target_arch = "wasm32"))]
                    fn wit_import() {
                        unreachable!()
                    }
                    wit_import();
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn noop2() {
                unsafe {
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "testing:noop/noop")]
                    extern "C" {
                        #[link_name = "noop2"]
                        fn wit_import();
                    }

                    #[cfg(not(target_arch = "wasm32"))]
                    fn wit_import() {
                        unreachable!()
                    }
                    wit_import();
                }
            }
        }
    }
}
pub mod exports {
    pub mod testing {
        pub mod noop_workflow {
            #[allow(clippy::all)]
            pub mod workflow {
                #[used]
                #[doc(hidden)]
                #[cfg(target_arch = "wasm32")]
                static __FORCE_SECTION_REF: fn() =
                    super::super::super::super::__link_custom_section_describing_imports;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_noopa_cabi<T: Guest>(arg0: i32) {
                    T::noopa(arg0 as u32);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_noopha_cabi<T: Guest>(arg0: i32) {
                    T::noopha(arg0 as u32);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_noopw_cabi<T: Guest>(arg0: i32) {
                    T::noopw(arg0 as u32);
                }
                pub trait Guest {
                    fn noopa(iterations: u32);
                    fn noopha(iterations: u32);
                    fn noopw(iterations: u32);
                }
                #[doc(hidden)]

                macro_rules! __export_testing_noop_workflow_workflow_cabi{
    ($ty:ident with_types_in $($path_to_types:tt)*) => (const _: () = {

      #[export_name = "testing:noop-workflow/workflow#noopa"]
      unsafe extern "C" fn export_noopa(arg0: i32,) {
        $($path_to_types)*::_export_noopa_cabi::<$ty>(arg0)
      }
      #[export_name = "testing:noop-workflow/workflow#noopha"]
      unsafe extern "C" fn export_noopha(arg0: i32,) {
        $($path_to_types)*::_export_noopha_cabi::<$ty>(arg0)
      }
      #[export_name = "testing:noop-workflow/workflow#noopw"]
      unsafe extern "C" fn export_noopw(arg0: i32,) {
        $($path_to_types)*::_export_noopw_cabi::<$ty>(arg0)
      }
    };);
  }
                #[doc(hidden)]
                pub(crate) use __export_testing_noop_workflow_workflow_cabi;
            }
        }
    }
}
mod _rt {

    pub fn as_i64<T: AsI64>(t: T) -> i64 {
        t.as_i64()
    }

    pub trait AsI64 {
        fn as_i64(self) -> i64;
    }

    impl<'a, T: Copy + AsI64> AsI64 for &'a T {
        fn as_i64(self) -> i64 {
            (*self).as_i64()
        }
    }

    impl AsI64 for i64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }

    impl AsI64 for u64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
}

/// Generates `#[no_mangle]` functions to export the specified type as the
/// root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]

macro_rules! __export_any_impl {
  ($ty:ident) => (self::export!($ty with_types_in self););
  ($ty:ident with_types_in $($path_to_types_root:tt)*) => (
  $($path_to_types_root)*::exports::testing::noop_workflow::workflow::__export_testing_noop_workflow_workflow_cabi!($ty with_types_in $($path_to_types_root)*::exports::testing::noop_workflow::workflow);
  )
}
#[doc(inline)]
pub(crate) use __export_any_impl as export;

#[cfg(target_arch = "wasm32")]
#[link_section = "component-type:wit-bindgen:0.21.0:any:encoded world"]
#[doc(hidden)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 376] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xfe\x01\x01A\x02\x01\
A\x06\x01B\x03\x01@\0\x01\0\x04\0\x04noop\x01\0\x04\0\x05noop2\x01\0\x03\x01\x11\
testing:noop/noop\x05\0\x01B\x04\x01@\x01\x06millisw\x01\0\x04\0\x05sleep\x01\0\x01\
@\0\x01\0\x04\0\x04noop\x01\x01\x03\x01&my-org:workflow-engine/host-activities\x05\
\x01\x01B\x04\x01@\x01\x0aiterationsy\x01\0\x04\0\x05noopa\x01\0\x04\0\x06noopha\
\x01\0\x04\0\x05noopw\x01\0\x04\x01\x1etesting:noop-workflow/workflow\x05\x02\x04\
\x01\x19testing:noop-workflow/any\x04\0\x0b\x09\x01\0\x03any\x03\0\0\0G\x09produ\
cers\x01\x0cprocessed-by\x02\x0dwit-component\x070.201.0\x10wit-bindgen-rust\x06\
0.21.0";

#[inline(never)]
#[doc(hidden)]
#[cfg(target_arch = "wasm32")]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
