package testing:http-obelisk-ext;

interface http-get {
    use obelisk:types/execution@1.1.0.{execution-id, join-set-id, execution-error};

    get-successful-submit: func(join-set-id: borrow<join-set-id>, url: string) -> execution-id;

    get-successful-await-next: func(join-set-id: borrow<join-set-id>) -> result<tuple<execution-id, result<string, string>>, tuple<execution-id, execution-error>>;
}
