[package]
name = "test-programs-fibo-webhook"
version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
wit-bindgen-rt = { workspace = true, features = ["bitflags"] }

[lib]
crate-type = ["cdylib"]

[package.metadata.component.target.dependencies]
"wasi:http".path = "wit/deps/http/"
"wasi:random".path = "wit/deps/random/"
"wasi:cli".path = "wit/deps/cli"
"wasi:io".path = "wit/deps/io"
"wasi:clocks".path = "wit/deps/clocks"
"wasi:filesystem".path = "wit/deps/filesystem"
"wasi:sockets".path = "wit/deps/sockets"
"testing:fibo-workflow".path = "../workflow/wit/ifc"
"testing:fibo-workflow-obelisk-ext".path = "../workflow/wit/ifc-ext"

[lints]
rust.unused_imports = "allow"
clippy.wrong_self_convention = "allow"
clippy.unnecessary_cast = "allow"
