[package]
name = "test-programs-fibo-webhook"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
wit-bindgen.workspace = true

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true
