package testing:process;

interface process {
    touch: func() -> result<_, string>;

    stdio: func() -> result<_, string>;

    kill: func() -> result<_, string>;

    exec-sleep: func() -> result<u32, string>;

    subscribe-wait: func() -> result<_, string>;

    get-env: func() -> result<list<tuple<string,string>>, string>;

}
