[build]
release = false
filehash = true
dist = "dist-dev"

[serve]
port = 8081

[[proxy]]
# Proxy the gRPC requests to the "webui" web server as configured in obelisk.toml .
# Only /api prefixed requests should be proxied:
# Remove /api path prefix using the rewrite rule, then add it back.
rewrite = "/api"
backend = "http://127.0.0.1:8080/api"

[tools]
wasm_opt = "version_120"
wasm_bindgen = "0.2.95"
