[build]
release = false
filehash = true

[serve]
port = 8081

[[proxy]]
backend = "http://127.0.0.1:5005" # Address to proxy requests to
rewrite = "/api"                  # Remove /api path prefix

[tools]
wasm_opt = "version_118"
wasm_bindgen = "0.2.95"
tailwindcss = "3.4.13"
