package obelisk:types@1.1.0;

interface time {

    variant duration {
        milliseconds(u64),
        seconds(u64),
        minutes(u32),
        hours(u32),
        days(u32),
    }

    /// A time and date in seconds plus nanoseconds.
    // Extracted from wasi:clocks@0.2.0 to avoid dependency on wasi:io
    record datetime {
        seconds: u64,
        nanoseconds: u32,
    }

    variant schedule-at {
        now,
        at(datetime),
        in(duration),
    }
}

interface execution {
    resource join-set-id {
        id: func() -> string;
        // TODO: sleep-submit
        // TODO: await-next
    }
    record execution-id {
        id: string,
    }

    record delay-id {
        id: string,
    }

    variant execution-error {
        // FIXME: keep only one variant `unknown`
        // NB: Update wasm_tools' error_tuple as well.
        activity-trap(string),
        permanent-timeout,
    }

    variant stub-error {
        not-found,
        ffqn-mismatch,
        // stubbed execution must not contain any execution log entries except for the `Created` event.
        conflict,
    }
}
