package testing:fibo-workflow;

interface workflow {
    fibow: func(n: u8, iterations: u32) -> u64;
    fiboa: func(n: u8, iterations: u32) -> u64;
}

world any {
    import testing:fibo/fibo;
    export workflow;
}
