package testing:fibo-workflow;

interface workflow {
    fibow: func(n: u8, iterations: u32) -> u64;
    fiboa: func(n: u8, iterations: u32) -> u64;
    fiboa-concurrent: func(n: u8, iterations: u32) -> u64;
}

interface workflow-nesting {
    fibo-nested-workflow: func(n: u8) -> u64;
}

world any {
    import testing:fibo/fibo;
    import my-org:workflow-engine/host-activities;
    import testing:fibo-obelisk-ext/fibo;
    export workflow;
    import workflow;
    export workflow-nesting;
}
