package testing:sleep-workflow-obelisk-ext;

interface workflow {
    use obelisk:workflow/host-activities.{scheduled-at, duration};

    reschedule-schedule: func(schedule: scheduled-at, nanos: duration, iterations: u8) -> string;
}
