package testing:sleep-workflow-obelisk-ext;

interface workflow {
    use obelisk:types/execution.{execution-id};
    use obelisk:types/time.{duration, schedule-at};

    reschedule-schedule: func(schedule: schedule-at, duration: duration, iterations: u8) -> execution-id;
}
