package testing:sleep-workflow-obelisk-ext;

interface workflow {
    use obelisk:types/time.{schedule-at, duration};

    reschedule-schedule: func(schedule: schedule-at, nanos: duration, iterations: u8) -> string;
}
