package testing:sleep-workflow;

interface workflow {
    use obelisk:types/time.{duration};

    sleep-host-activity: func(duration: duration);
    sleep-activity: func(duration: duration);
    reschedule: func(duration: duration, iterations: u8);
}
