package testing:sleep-workflow;

interface workflow {
    use obelisk:types/time.{duration};
    sleep-host-activity: func(millis: u64);
    sleep-activity: func(millis: u64);
    reschedule: func(nanos: duration, iterations: u8);
}
