package testing:serde;

interface serde {

    record my-record {
        a: bool,
        image: string,
        b: bool,
        opt: option<bool>,
    }

    rec: func(my-record: my-record) -> result<my-record>;

    variant my-variant {
        var1(option<bool>)
    }

    var: func(my-variant: my-variant) -> result<my-variant>;

    variant my-error {
        foo,
        execution-failed
    }
    trap: func() -> result<_, my-error>;

}

