package obelisk:types@3.0.0;

@since(version = 3.0.0)
interface time {

    @since(version = 3.0.0)
    variant duration {
        milliseconds(u64),
        seconds(u64),
        minutes(u32),
        hours(u32),
        days(u32),
    }

    /// A time and date in seconds plus nanoseconds.
    // Extracted from wasi:clocks@0.2.0 to avoid dependency on wasi:io
    @since(version = 3.0.0)
    record datetime {
        seconds: u64,
        nanoseconds: u32,
    }

    @since(version = 3.0.0)
    variant schedule-at {
        now,
        at(datetime),
        in(duration),
    }
}

@since(version = 3.0.0)
interface execution {

    /// Join set resouce.
    @since(version = 3.0.0)
    resource join-set {
        @since(version = 3.0.0)
        id: func() -> string;
    }

    @since(version = 3.0.0)
    record execution-id {
        id: string,
    }

    @since(version = 3.0.0)
    record delay-id {
        id: string,
    }

    @since(version = 3.0.0)
    record function {
        // `namespace:pkg_name/ifc_name` or `namespace:pkg_name/ifc_name@version`
        interface-name: string,
        function-name: string,
    }

    @since(version = 3.0.0)
    variant response-id {
        execution-id(execution-id),
        delay-id(delay-id),
    }

    @since(version = 3.0.0)
    record function-mismatch {
        /// Workflow requested function
        specified-function: function,
        /// What was found actually during execution. None if delay was found as next unprocessed response.
        actual-function: option<function>,
        actual-id: response-id,
    }

    /// Error that is thrown by `-await-next` extension functions.
    @since(version = 3.0.0)
    variant await-next-extension-error {
        /// All submitted requests and their responses of specified function and join set were already processed.
        all-processed,
        /// Execution response was awaited and marked as processed, but it belongs to a different function.
        /// This can happen when join set contains responses of multiple functions or delay requests.
        function-mismatch(function-mismatch),
    }

    /// Error variants that may occur when calling `-get` extension functions.
    @since(version = 3.0.0)
    variant get-extension-error {
        /// Execution is found in processed responses, but it belongs to a different function.
        /// This can happen when join set contains responses of multiple functions.
        function-mismatch(function-mismatch),
        /// Processed responses do not contain the specified execution ID.
        /// This can happen if the execution was not marked as processed (awaited), or
        /// the execution ID does not belong to the specified join set.
        not-found-in-processed-responses,
    }

    /// Error variants that may occur when calling `-invoke` extension functions.
    @since(version = 3.0.0)
    variant invoke-extension-error {
        invalid-name(string),
    }

    /// Error variants that may occur when calling `-stub` extension functions.
    @since(version = 3.0.0)
    variant stub-error {
        /// Conflict can happen when a second writer attempts to stub a value, while the
        /// value is not equal to the already stubbed value.
        conflict,
    }
}
