package testing:http-workflow;

interface workflow {
    get: func(authority: string, path: string) -> result<string, string>;
    get-successful: func(authority: string, path: string) -> result<string, string>;
}

world any {
    import testing:http/http-get;
    export workflow;
}
