package testing:sleep-obelisk-ext;

interface sleep {
    use obelisk:types/time@1.0.0.{duration};
    use obelisk:types/execution@1.0.0.{join-set-id, execution-id};

    sleep-submit: func(join-set-id: borrow<join-set-id>, duration: duration) -> execution-id;
}
