# git cliff --unreleased --tag v0.42.0 --prepend CHANGELOG.md

[changelog]
header = """# Changelog
All notable changes to this project will be documented in this file.

## [Unreleased]
"""
body = """

{% macro print_commit(commit) -%}
    - {% if commit.scope %}*({{ commit.scope }})* {% endif %}\
      {% if commit.breaking %}[**breaking**] {% endif %}\
      {{ commit.message | upper_first }} - \
      ([{{ commit.id | truncate(length=7, end="") }}](https://github.com/obeli-sk/obelisk/commit/{{ commit.id }}))\
{% endmacro -%}

{% if version %}\
    {% if previous.version %}\
        ## [{{ version | trim_start_matches(pat="v") }}](https://github.com/obeli-sk/obelisk/compare/{{ previous.version }}...{{ version }})
    {% else %}\
        ## [{{ version | trim_start_matches(pat="v") }}]
    {% endif %}\
{% endif %}\

{% for group, commits in commits
| filter(attribute="merge_commit", value=false)
| unique(attribute="message")
| group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits
    | filter(attribute="scope")
    | sort(attribute="scope") %}
        {{ self::print_commit(commit=commit) }}
    {%- endfor -%}
    {% raw %}\n{% endraw %}\
    {%- for commit in commits %}
        {%- if not commit.scope -%}
            {{ self::print_commit(commit=commit) }}
        {% endif -%}
    {% endfor -%}
{% endfor %}\n
"""

[git]
conventional_commits = true
filter_unconventional = false
commit_parsers = [
    { message = "^feat|^perf", group = "<!-- 0 -->Added" },
    { message = "^fix", group = "<!-- 1 -->Fixed" },
    { message = "^refactor|^r", group = "<!-- 7 -->Changed" },
    { message = "^test", skip = true },
    { message = "^style", skip = true },
    { message = "^chore", skip = true },
    { message = "^ci", skip = true },
    { message = "^build", skip = true },
    { message = "^logging", skip = true },
    { message = "^tracing", skip = true },
]
tag_pattern = "v[0-9].*"
