#!/usr/bin/env bash

# Dumps the consolidated SQL schema produced by the embedded migrations, for both
# database backends, into `assets/schemas/sql/`. We only check in migrations, so a
# whole-schema view is otherwise hard to review; regenerate this after adding a
# migration. Requires `obelisk` on PATH; sqlite + postgresql tools come from the
# devshell (`nix develop`).

set -euo pipefail
cd "$(dirname "$0")/.."

OUT_DIR="assets/schemas/sql"
HEADER="-- Generated by scripts/dump-sql-schema.sh from the embedded migrations. Do not edit."

for tool in obelisk sqlite3 pg_dump initdb pg_ctl; do
  if ! command -v "$tool" >/dev/null 2>&1; then
    echo "error: '$tool' not found on PATH (obelisk must be built and on PATH; run inside 'nix develop' for the db tools)" >&2
    exit 1
  fi
done

mkdir -p "$OUT_DIR"

WORK=$(mktemp -d)
PG_DATA="$WORK/pg-data"
PG_SOCK="$WORK/pg-sock"

cleanup() {
  # Stop postgres if it is still running, then drop the scratch dir.
  if [ -f "$PG_DATA/postmaster.pid" ]; then
    pg_ctl -D "$PG_DATA" -m immediate stop >/dev/null 2>&1 || true
  fi
  rm -rf "$WORK"
}
trap cleanup EXIT

# `server verify` applies the embedded migrations to the configured database and
# exits; `-d` needs a deployment, and an empty file verifies as an empty deployment.
: > "$WORK/empty-deploy.toml"

echo "Dumping sqlite schema..."
cat >"$WORK/sqlite.toml" <<EOF
api.enabled = false
webui.enabled = false
database.sqlite.directory = "$WORK/sqlite-db"
EOF
OBELISK_APP_NAME=schema-dump obelisk server verify -s "$WORK/sqlite.toml" -d "$WORK/empty-deploy.toml"
{
  echo "$HEADER"
  echo
  sqlite3 "$WORK/sqlite-db/obelisk.sqlite" .schema
} >"$OUT_DIR/sqlite.sql"

echo "Dumping postgres schema..."
mkdir -p "$PG_SOCK"
initdb -U postgres -A trust "$PG_DATA" >/dev/null
# Unix-socket only (no TCP) so parallel runs never collide on a port.
pg_ctl -D "$PG_DATA" -o "-c listen_addresses= -k $PG_SOCK" -l "$WORK/pg.log" -w start >/dev/null
cat >"$WORK/postgres.toml" <<EOF
api.enabled = false
webui.enabled = false
[database.postgres]
host = "$PG_SOCK"
user = "postgres"
password = ""
db_name = "obelisk"
provision_policy = "auto"
EOF
OBELISK_APP_NAME=schema-dump obelisk server verify -s "$WORK/postgres.toml" -d "$WORK/empty-deploy.toml"
{
  echo "$HEADER"
  # Drop lines that vary per run (\restrict nonce) or per tool version (dump-version
  # comments) so the checked-in dump only changes when the schema does.
  pg_dump -h "$PG_SOCK" -U postgres --schema-only --no-owner --no-privileges obelisk \
    | grep -vE '^\\(restrict|unrestrict)|^-- Dumped (from database|by pg_dump) version'
} >"$OUT_DIR/postgres.sql"

echo "Wrote $OUT_DIR/sqlite.sql and $OUT_DIR/postgres.sql"
