#!/usr/bin/env bash

# Regenerates everything under `assets/schemas/`: TOML/deployment JSON schemas and the
# consolidated SQL schema dumps of the embedded migrations. Run inside `nix develop`.

set -exuo pipefail
cd "$(dirname "$0")/.."

mkdir -p assets/schemas/toml

cargo test --bin obelisk command::generate::tests::update_ -- --ignored

# SQL schema: we only check in migrations, so a whole-schema view is otherwise hard to review.
cargo build --bin obelisk
OBELISK="$(realpath "${CARGO_TARGET_DIR:-target}/debug/obelisk")"
SQL_DIR="assets/schemas/sql"
HEADER="-- Generated by scripts/update-schemas.sh from the embedded migrations. Do not edit."
mkdir -p "$SQL_DIR"

WORK=$(mktemp -d)
PG_DATA="$WORK/pg-data"
PG_SOCK="$WORK/pg-sock"

cleanup() {
  if [ -f "$PG_DATA/postmaster.pid" ]; then
    pg_ctl -D "$PG_DATA" -m immediate stop >/dev/null 2>&1 || true
  fi
  rm -rf "$WORK"
}
trap cleanup EXIT

# `server verify` applies the embedded migrations and exits; an empty file verifies as an empty deployment.
: > "$WORK/empty-deploy.toml"

cat >"$WORK/sqlite.toml" <<TOML
api.enabled = false
webui.enabled = false
database.sqlite.directory = "$WORK/sqlite-db"
TOML
OBELISK_APP_NAME=schema-dump "$OBELISK" server verify -s "$WORK/sqlite.toml" -d "$WORK/empty-deploy.toml"
{
  echo "$HEADER"
  echo
  sqlite3 "$WORK/sqlite-db/obelisk.sqlite" .schema
} >"$SQL_DIR/sqlite.sql"

mkdir -p "$PG_SOCK"
initdb -U postgres -A trust "$PG_DATA" >/dev/null
# Unix-socket only (no TCP) so parallel runs never collide on a port.
pg_ctl -D "$PG_DATA" -o "-c listen_addresses= -k $PG_SOCK" -l "$WORK/pg.log" -w start >/dev/null
cat >"$WORK/postgres.toml" <<TOML
api.enabled = false
webui.enabled = false
[database.postgres]
host = "$PG_SOCK"
user = "postgres"
password = ""
db_name = "obelisk"
provision_policy = "auto"
TOML
OBELISK_APP_NAME=schema-dump "$OBELISK" server verify -s "$WORK/postgres.toml" -d "$WORK/empty-deploy.toml"
{
  echo "$HEADER"
  # Drop lines that vary per run (\restrict nonce) or per pg_dump version so the dump only changes with the schema.
  pg_dump -h "$PG_SOCK" -U postgres --schema-only --no-owner --no-privileges obelisk \
    | grep -vE '^\\(restrict|unrestrict)|^-- Dumped (from database|by pg_dump) version'
} >"$SQL_DIR/postgres.sql"
