package testing:http-obelisk-ext;

interface http-get {
    use obelisk:types/execution.{execution-id, execution-error};

    get-successful-submit: func(join-set-id: string, url: string) -> string;

    get-successful-await-next: func(join-set-id: string) -> result<tuple<execution-id, result<string, string>>, tuple<execution-id, execution-error>>;
}
