-- Generated by scripts/update-schemas.sh from the embedded migrations. Do not edit.
--
-- PostgreSQL database dump
--



SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: refinery_schema_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.refinery_schema_history (
    version integer NOT NULL,
    name character varying(255),
    applied_on character varying(255),
    checksum character varying(255)
);


--
-- Name: t_component_metadata; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_component_metadata (
    component_digest bytea NOT NULL,
    imports_json jsonb NOT NULL,
    exports_json jsonb NOT NULL,
    wit text NOT NULL,
    wit_origin smallint NOT NULL,
    CONSTRAINT t_component_metadata_wit_origin_check CHECK ((wit_origin = ANY (ARRAY[1, 2, 3])))
);


--
-- Name: t_component_source; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_component_source (
    component_digest bytea NOT NULL,
    frame_key text NOT NULL,
    is_suffix boolean NOT NULL,
    digest text NOT NULL
);


--
-- Name: t_delay; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_delay (
    execution_id text NOT NULL,
    join_set_id text NOT NULL,
    delay_id text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    is_paused boolean DEFAULT false NOT NULL
);


--
-- Name: t_deployment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_deployment (
    deployment_id character varying(30) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    last_active_at timestamp with time zone,
    status character varying(8) DEFAULT 'inactive'::text NOT NULL,
    deployment_toml text CONSTRAINT t_deployment_config_json_not_null NOT NULL,
    obelisk_version text NOT NULL,
    created_by text,
    description character varying(1024),
    digest character varying(71) DEFAULT 'sha256:0000000000000000000000000000000000000000000000000000000000000000'::text NOT NULL,
    inactive_at timestamp with time zone,
    last_active_app_config_digest text
);


--
-- Name: t_deployment_component; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_deployment_component (
    deployment_id character varying(30) NOT NULL,
    component_name text NOT NULL,
    component_type character varying(16) NOT NULL,
    component_digest bytea NOT NULL
);


--
-- Name: t_deployment_component_file; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_deployment_component_file (
    deployment_id character varying(30) NOT NULL,
    component_name text NOT NULL,
    path text NOT NULL,
    role character varying(16) NOT NULL,
    CONSTRAINT t_deployment_component_file_role_check CHECK (((role)::text = ANY ((ARRAY['wasm_component'::character varying, 'exec_program'::character varying, 'js_entrypoint'::character varying, 'js_module'::character varying, 'backtrace_source'::character varying, 'wit_source'::character varying])::text[])))
);


--
-- Name: t_deployment_file; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_deployment_file (
    deployment_id character varying(30) NOT NULL,
    digest character varying(71) NOT NULL,
    path text NOT NULL
);


--
-- Name: t_execution_backtrace; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_execution_backtrace (
    execution_id text NOT NULL,
    component_id jsonb NOT NULL,
    version_min_including bigint NOT NULL,
    version_max_excluding bigint NOT NULL,
    backtrace_hash bytea NOT NULL,
    CONSTRAINT t_execution_backtrace_version_max_excluding_check CHECK ((version_max_excluding >= 0)),
    CONSTRAINT t_execution_backtrace_version_min_including_check CHECK ((version_min_including >= 0))
);


--
-- Name: t_execution_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_execution_log (
    execution_id text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    "json_value" json NOT NULL,
    version bigint NOT NULL,
    variant character varying(32) NOT NULL,
    join_set_id text,
    history_event_type character varying(20) GENERATED ALWAYS AS (("json_value" #>> '{history_event,event,type}'::text[])) STORED,
    CONSTRAINT t_execution_log_version_check CHECK ((version >= 0))
);


--
-- Name: t_file; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_file (
    digest character varying(71) NOT NULL,
    content bytea NOT NULL,
    size bigint NOT NULL
);


--
-- Name: t_join_set_response; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_join_set_response (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    execution_id text NOT NULL,
    join_set_id text NOT NULL,
    delay_id text,
    delay_success boolean,
    child_execution_id text,
    finished_version bigint,
    seq bigint,
    CONSTRAINT t_join_set_response_finished_version_check CHECK ((finished_version >= 0))
);


--
-- Name: t_join_set_response_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.t_join_set_response ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.t_join_set_response_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: t_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_log (
    id bigint NOT NULL,
    execution_id text NOT NULL,
    run_id character varying(30) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    level integer,
    message text,
    stream_type integer,
    payload bytea
);


--
-- Name: t_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.t_log ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.t_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: t_state; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_state (
    execution_id text NOT NULL,
    is_top_level boolean NOT NULL,
    corresponding_version bigint NOT NULL,
    ffqn text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    component_id_input_digest bytea NOT NULL,
    component_type character varying(16) NOT NULL,
    first_scheduled_at timestamp with time zone NOT NULL,
    deployment_id character varying(30) NOT NULL,
    pending_expires_finished timestamp with time zone NOT NULL,
    state character varying(20) NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    intermittent_event_count bigint NOT NULL,
    max_retries bigint,
    retry_exp_backoff_millis bigint,
    last_lock_version bigint,
    executor_id character varying(30),
    run_id character varying(30),
    join_set_id text,
    join_set_closing boolean,
    result_kind jsonb,
    incompatible_digest bytea,
    lifecycle text DEFAULT 'active'::text NOT NULL,
    tombstoned boolean DEFAULT false NOT NULL,
    CONSTRAINT t_state_corresponding_version_check CHECK ((corresponding_version >= 0)),
    CONSTRAINT t_state_intermittent_event_count_check CHECK ((intermittent_event_count >= 0)),
    CONSTRAINT t_state_last_lock_version_check CHECK ((last_lock_version >= 0)),
    CONSTRAINT t_state_lifecycle_check CHECK ((lifecycle = ANY (ARRAY['active'::text, 'paused'::text, 'cancelling'::text]))),
    CONSTRAINT t_state_max_retries_check CHECK ((max_retries >= 0)),
    CONSTRAINT t_state_retry_exp_backoff_millis_check CHECK ((retry_exp_backoff_millis >= 0))
);


--
-- Name: t_system_event; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_system_event (
    event_id character varying(64) NOT NULL,
    node_run_id character varying(34) CONSTRAINT t_system_event_server_run_id_not_null NOT NULL,
    created_at timestamp with time zone NOT NULL,
    level character varying(7) NOT NULL,
    code character varying(64) NOT NULL,
    execution_id character varying(1024),
    deployment_id character varying(64),
    dedupe_key character varying(512),
    cas_digest character varying(71),
    details jsonb NOT NULL,
    app_config_digest text,
    CONSTRAINT t_system_event_details_check CHECK ((pg_column_size(details) <= 4096)),
    CONSTRAINT t_system_event_level_check CHECK (((level)::text = ANY ((ARRAY['debug'::character varying, 'info'::character varying, 'warning'::character varying, 'error'::character varying])::text[])))
);


--
-- Name: t_wasm_backtrace; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.t_wasm_backtrace (
    backtrace_hash bytea NOT NULL,
    wasm_backtrace jsonb NOT NULL
);


--
-- Name: refinery_schema_history refinery_schema_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refinery_schema_history
    ADD CONSTRAINT refinery_schema_history_pkey PRIMARY KEY (version);


--
-- Name: t_component_metadata t_component_metadata_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_component_metadata
    ADD CONSTRAINT t_component_metadata_pkey PRIMARY KEY (component_digest);


--
-- Name: t_component_source t_component_source_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_component_source
    ADD CONSTRAINT t_component_source_pkey PRIMARY KEY (component_digest, frame_key, is_suffix);


--
-- Name: t_delay t_delay_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_delay
    ADD CONSTRAINT t_delay_pkey PRIMARY KEY (execution_id, join_set_id, delay_id);


--
-- Name: t_deployment_component_file t_deployment_component_file_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_deployment_component_file
    ADD CONSTRAINT t_deployment_component_file_pkey PRIMARY KEY (deployment_id, component_name, path);


--
-- Name: t_deployment_component t_deployment_component_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_deployment_component
    ADD CONSTRAINT t_deployment_component_pkey PRIMARY KEY (deployment_id, component_name);


--
-- Name: t_deployment_file t_deployment_file_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_deployment_file
    ADD CONSTRAINT t_deployment_file_pkey PRIMARY KEY (deployment_id, path);


--
-- Name: t_deployment t_deployment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_deployment
    ADD CONSTRAINT t_deployment_pkey PRIMARY KEY (deployment_id);


--
-- Name: t_execution_backtrace t_execution_backtrace_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_execution_backtrace
    ADD CONSTRAINT t_execution_backtrace_pkey PRIMARY KEY (execution_id, version_min_including, version_max_excluding);


--
-- Name: t_execution_log t_execution_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_execution_log
    ADD CONSTRAINT t_execution_log_pkey PRIMARY KEY (execution_id, version);


--
-- Name: t_file t_file_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_file
    ADD CONSTRAINT t_file_pkey PRIMARY KEY (digest);


--
-- Name: t_join_set_response t_join_set_response_execution_id_join_set_id_delay_id_child_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_join_set_response
    ADD CONSTRAINT t_join_set_response_execution_id_join_set_id_delay_id_child_key UNIQUE (execution_id, join_set_id, delay_id, child_execution_id);


--
-- Name: t_join_set_response t_join_set_response_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_join_set_response
    ADD CONSTRAINT t_join_set_response_pkey PRIMARY KEY (id);


--
-- Name: t_log t_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_log
    ADD CONSTRAINT t_log_pkey PRIMARY KEY (id);


--
-- Name: t_state t_state_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_state
    ADD CONSTRAINT t_state_pkey PRIMARY KEY (execution_id);


--
-- Name: t_system_event t_system_event_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_system_event
    ADD CONSTRAINT t_system_event_pkey PRIMARY KEY (event_id);


--
-- Name: t_wasm_backtrace t_wasm_backtrace_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_wasm_backtrace
    ADD CONSTRAINT t_wasm_backtrace_pkey PRIMARY KEY (backtrace_hash);


--
-- Name: idx_join_set_response_unique_child_id; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_join_set_response_unique_child_id ON public.t_join_set_response USING btree (child_execution_id) WHERE (child_execution_id IS NOT NULL);


--
-- Name: idx_join_set_response_unique_delay_id; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_join_set_response_unique_delay_id ON public.t_join_set_response USING btree (delay_id) WHERE (delay_id IS NOT NULL);


--
-- Name: idx_t_delay_expires_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_t_delay_expires_at ON public.t_delay USING btree (expires_at) WHERE (NOT is_paused);


--
-- Name: idx_t_deployment_component_component_digest; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_t_deployment_component_component_digest ON public.t_deployment_component USING btree (component_digest);


--
-- Name: idx_t_deployment_component_deployment_digest; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_t_deployment_component_deployment_digest ON public.t_deployment_component USING btree (deployment_id, component_digest);


--
-- Name: idx_t_deployment_component_deployment_list; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_t_deployment_component_deployment_list ON public.t_deployment_component USING btree (deployment_id, component_type, component_name);


--
-- Name: idx_t_deployment_component_file_path; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_t_deployment_component_file_path ON public.t_deployment_component_file USING btree (deployment_id, path);


--
-- Name: idx_t_deployment_file_digest; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_t_deployment_file_digest ON public.t_deployment_file USING btree (digest);


--
-- Name: idx_t_deployment_inactive_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_t_deployment_inactive_at ON public.t_deployment USING btree (inactive_at, deployment_id) WHERE ((status)::text = 'inactive'::text);


--
-- Name: idx_t_deployment_single_active; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_t_deployment_single_active ON public.t_deployment USING btree ((1)) WHERE ((status)::text = 'active'::text);


--
-- Name: idx_t_deployment_single_enqueued; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_t_deployment_single_enqueued ON public.t_deployment USING btree ((1)) WHERE ((status)::text = 'enqueued'::text);


--
-- Name: idx_t_deployment_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_t_deployment_status ON public.t_deployment USING btree (status);


--
-- Name: idx_t_execution_backtrace_backtrace_hash; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_t_execution_backtrace_backtrace_hash ON public.t_execution_backtrace USING btree (backtrace_hash);


--
-- Name: idx_t_execution_backtrace_execution_id_version; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_t_execution_backtrace_execution_id_version ON public.t_execution_backtrace USING btree (execution_id, version_min_including, version_max_excluding);


--
-- Name: idx_t_execution_log_execution_id_join_set; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_t_execution_log_execution_id_join_set ON public.t_execution_log USING btree (execution_id, join_set_id, history_event_type) WHERE ((history_event_type)::text = 'join_next'::text);


--
-- Name: idx_t_execution_log_execution_id_variant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_t_execution_log_execution_id_variant ON public.t_execution_log USING btree (execution_id, variant);


--
-- Name: idx_t_execution_log_execution_id_version; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_t_execution_log_execution_id_version ON public.t_execution_log USING btree (execution_id, version);


--
-- Name: idx_t_join_set_response_execution_id_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_t_join_set_response_execution_id_id ON public.t_join_set_response USING btree (execution_id, id);


--
-- Name: idx_t_join_set_response_execution_id_seq; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_t_join_set_response_execution_id_seq ON public.t_join_set_response USING btree (execution_id, seq);


--
-- Name: idx_t_log_execution_id_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_t_log_execution_id_id ON public.t_log USING btree (execution_id, id);


--
-- Name: idx_t_log_execution_id_run_id_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_t_log_execution_id_run_id_created_at ON public.t_log USING btree (execution_id, run_id, created_at);


--
-- Name: idx_t_state_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_t_state_created_at ON public.t_state USING btree (created_at);


--
-- Name: idx_t_state_deployment_state; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_t_state_deployment_state ON public.t_state USING btree (deployment_id, is_top_level, state, lifecycle, pending_expires_finished, result_kind);


--
-- Name: idx_t_state_execution_id_is_root; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_t_state_execution_id_is_root ON public.t_state USING btree (execution_id, is_top_level);


--
-- Name: idx_t_state_expired_locks; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_t_state_expired_locks ON public.t_state USING btree (pending_expires_finished) WHERE ((state)::text = 'locked'::text);


--
-- Name: idx_t_state_ffqn; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_t_state_ffqn ON public.t_state USING btree (ffqn);


--
-- Name: idx_t_state_lock_pending_auto; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_t_state_lock_pending_auto ON public.t_state USING btree (state, pending_expires_finished, ffqn, incompatible_digest) WHERE ((state)::text = 'pending_at'::text);


--
-- Name: idx_t_state_lock_pending_by_component; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_t_state_lock_pending_by_component ON public.t_state USING btree (state, pending_expires_finished, component_id_input_digest) WHERE ((state)::text = 'pending_at'::text);


--
-- Name: idx_t_state_lock_pending_by_ffqn; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_t_state_lock_pending_by_ffqn ON public.t_state USING btree (state, pending_expires_finished, ffqn) WHERE ((state)::text = 'pending_at'::text);


--
-- Name: idx_t_state_retention_updated_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_t_state_retention_updated_at ON public.t_state USING btree (updated_at, execution_id) WHERE ((is_top_level = true) AND (tombstoned = false));


--
-- Name: idx_t_state_tombstoned_roots; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_t_state_tombstoned_roots ON public.t_state USING btree (execution_id) WHERE ((is_top_level = true) AND (tombstoned = true));


--
-- Name: t_system_event_code_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX t_system_event_code_idx ON public.t_system_event USING btree (code, created_at DESC, event_id DESC);


--
-- Name: t_system_event_created_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX t_system_event_created_idx ON public.t_system_event USING btree (created_at DESC, event_id DESC);


--
-- Name: t_system_event_dedupe_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX t_system_event_dedupe_idx ON public.t_system_event USING btree (code, deployment_id, dedupe_key) WHERE (dedupe_key IS NOT NULL);


--
-- Name: t_system_event_deployment_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX t_system_event_deployment_idx ON public.t_system_event USING btree (deployment_id, created_at DESC, event_id DESC);


--
-- Name: t_system_event_node_run_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX t_system_event_node_run_idx ON public.t_system_event USING btree (node_run_id, event_id DESC);


--
-- Name: t_component_source t_component_source_digest_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_component_source
    ADD CONSTRAINT t_component_source_digest_fkey FOREIGN KEY (digest) REFERENCES public.t_file(digest);


--
-- Name: t_deployment_component t_deployment_component_component_digest_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_deployment_component
    ADD CONSTRAINT t_deployment_component_component_digest_fkey FOREIGN KEY (component_digest) REFERENCES public.t_component_metadata(component_digest);


--
-- Name: t_deployment_component t_deployment_component_deployment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_deployment_component
    ADD CONSTRAINT t_deployment_component_deployment_id_fkey FOREIGN KEY (deployment_id) REFERENCES public.t_deployment(deployment_id);


--
-- Name: t_deployment_component_file t_deployment_component_file_deployment_id_component_name_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_deployment_component_file
    ADD CONSTRAINT t_deployment_component_file_deployment_id_component_name_fkey FOREIGN KEY (deployment_id, component_name) REFERENCES public.t_deployment_component(deployment_id, component_name);


--
-- Name: t_deployment_component_file t_deployment_component_file_deployment_id_path_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_deployment_component_file
    ADD CONSTRAINT t_deployment_component_file_deployment_id_path_fkey FOREIGN KEY (deployment_id, path) REFERENCES public.t_deployment_file(deployment_id, path);


--
-- Name: t_deployment_file t_deployment_file_deployment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_deployment_file
    ADD CONSTRAINT t_deployment_file_deployment_id_fkey FOREIGN KEY (deployment_id) REFERENCES public.t_deployment(deployment_id);


--
-- Name: t_execution_backtrace t_execution_backtrace_backtrace_hash_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_execution_backtrace
    ADD CONSTRAINT t_execution_backtrace_backtrace_hash_fkey FOREIGN KEY (backtrace_hash) REFERENCES public.t_wasm_backtrace(backtrace_hash);


--
-- Name: t_system_event t_system_event_cas_digest_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.t_system_event
    ADD CONSTRAINT t_system_event_cas_digest_fkey FOREIGN KEY (cas_digest) REFERENCES public.t_file(digest);


--
-- PostgreSQL database dump complete
--


