-- Generated by scripts/update-schemas.sh from the embedded migrations. Do not edit.

CREATE TABLE refinery_schema_history(
             version int4 PRIMARY KEY,
             name VARCHAR(255),
             applied_on VARCHAR(255),
             checksum VARCHAR(255));
CREATE TABLE t_execution_log (
    execution_id TEXT NOT NULL,
    created_at TEXT NOT NULL,
    json_value TEXT NOT NULL,
    version INTEGER NOT NULL,
    variant TEXT NOT NULL,
    join_set_id TEXT,
    history_event_type TEXT GENERATED ALWAYS AS (json_value->>'$.history_event.event.type') STORED,
    PRIMARY KEY (execution_id, version)
) STRICT;
CREATE INDEX idx_t_execution_log_execution_id_version  ON t_execution_log (execution_id, version);
CREATE INDEX idx_t_execution_log_execution_id_variant  ON t_execution_log (execution_id, variant);
CREATE INDEX idx_t_execution_log_execution_id_join_set  ON t_execution_log (execution_id, join_set_id, history_event_type) WHERE history_event_type='join_next';
CREATE TABLE t_join_set_response (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at TEXT NOT NULL,
    execution_id TEXT NOT NULL,
    join_set_id TEXT NOT NULL,

    delay_id TEXT,
    delay_success INTEGER,

    child_execution_id TEXT,
    finished_version INTEGER, seq INTEGER,

    UNIQUE (execution_id, join_set_id, delay_id, child_execution_id)
) STRICT;
CREATE TABLE sqlite_sequence(name,seq);
CREATE INDEX idx_t_join_set_response_execution_id_id ON t_join_set_response (execution_id, id);
CREATE UNIQUE INDEX idx_join_set_response_unique_child_id
ON t_join_set_response (child_execution_id) WHERE child_execution_id IS NOT NULL;
CREATE UNIQUE INDEX idx_join_set_response_unique_delay_id
ON t_join_set_response (delay_id) WHERE delay_id IS NOT NULL;
CREATE TABLE t_state (
    execution_id TEXT NOT NULL,
    is_top_level INTEGER NOT NULL,
    corresponding_version INTEGER NOT NULL,
    ffqn TEXT NOT NULL,
    created_at TEXT NOT NULL,
    component_id_input_digest BLOB NOT NULL,
    component_type TEXT NOT NULL,
    first_scheduled_at TEXT NOT NULL,
    deployment_id TEXT NOT NULL,
    pending_expires_finished TEXT NOT NULL,
    state TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    intermittent_event_count INTEGER NOT NULL,

    max_retries INTEGER,
    retry_exp_backoff_millis INTEGER,
    last_lock_version INTEGER,
    executor_id TEXT,
    run_id TEXT,

    join_set_id TEXT,
    join_set_closing INTEGER,

    result_kind TEXT, incompatible_digest BLOB, lifecycle TEXT NOT NULL DEFAULT 'active'
    CHECK (lifecycle IN ('active', 'paused', 'cancelling')), tombstoned INTEGER NOT NULL DEFAULT FALSE,

    PRIMARY KEY (execution_id)
) STRICT;
CREATE INDEX idx_t_state_lock_pending_by_ffqn ON t_state (pending_expires_finished, ffqn) WHERE state = 'pending_at';
CREATE INDEX idx_t_state_lock_pending_by_component ON t_state (pending_expires_finished, component_id_input_digest) WHERE state = 'pending_at';
CREATE INDEX idx_t_state_expired_locks ON t_state (pending_expires_finished) WHERE state = 'locked';
CREATE INDEX idx_t_state_execution_id_is_root ON t_state (execution_id, is_top_level);
CREATE INDEX idx_t_state_ffqn ON t_state (ffqn);
CREATE INDEX idx_t_state_created_at ON t_state (created_at);
CREATE TABLE t_delay (
    execution_id TEXT NOT NULL,
    join_set_id TEXT NOT NULL,
    delay_id TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    is_paused INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (execution_id, join_set_id, delay_id)
) STRICT;
CREATE TABLE t_execution_backtrace (
    execution_id TEXT NOT NULL,
    component_id TEXT NOT NULL,
    version_min_including INTEGER NOT NULL,
    version_max_excluding INTEGER NOT NULL,
    backtrace_hash BLOB NOT NULL,

    PRIMARY KEY (
        execution_id,
        version_min_including,
        version_max_excluding
    ),
    FOREIGN KEY (backtrace_hash)
        REFERENCES t_wasm_backtrace(backtrace_hash)
) STRICT;
CREATE INDEX idx_t_execution_backtrace_execution_id_version
ON t_execution_backtrace (
    execution_id,
    version_min_including,
    version_max_excluding
);
CREATE TABLE t_wasm_backtrace (
    backtrace_hash BLOB NOT NULL,
    wasm_backtrace TEXT NOT NULL,

    PRIMARY KEY (backtrace_hash)
) STRICT;
CREATE TABLE t_log (
    id INTEGER PRIMARY KEY,
    execution_id TEXT NOT NULL,
    run_id TEXT NOT NULL,
    created_at TEXT NOT NULL,
    level INTEGER,
    message TEXT,
    stream_type INTEGER,
    payload BLOB
) STRICT;
CREATE INDEX idx_t_log_execution_id_run_id_created_at ON t_log (execution_id, run_id, created_at);
CREATE TABLE t_deployment (
    deployment_id TEXT NOT NULL PRIMARY KEY,
    created_at    TEXT NOT NULL,
    last_active_at TEXT,
    status        TEXT NOT NULL,
    deployment_toml      TEXT NOT NULL,
    obelisk_version  TEXT NOT NULL,
    created_by       TEXT
, description TEXT, digest TEXT NOT NULL DEFAULT 'sha256:0000000000000000000000000000000000000000000000000000000000000000', inactive_at TEXT, last_active_app_config_digest TEXT) STRICT;
CREATE INDEX idx_t_deployment_status ON t_deployment (status);
CREATE UNIQUE INDEX idx_t_deployment_single_active ON t_deployment ((1)) WHERE status = 'active';
CREATE UNIQUE INDEX idx_t_deployment_single_enqueued ON t_deployment ((1)) WHERE status = 'enqueued';
CREATE TABLE t_component_metadata (
    component_digest BLOB NOT NULL,
    imports_json     TEXT NOT NULL,
    exports_json     TEXT NOT NULL,
    wit              TEXT NOT NULL,
    wit_origin INTEGER NOT NULL DEFAULT 1 CHECK (wit_origin IN (1, 2, 3)),
    PRIMARY KEY (component_digest)
) STRICT;
CREATE TABLE t_deployment_component (
    deployment_id    TEXT NOT NULL,
    component_name   TEXT NOT NULL,
    component_type   TEXT NOT NULL,
    component_digest BLOB NOT NULL,
    PRIMARY KEY (deployment_id, component_name),
    FOREIGN KEY (deployment_id) REFERENCES t_deployment(deployment_id),
    FOREIGN KEY (component_digest) REFERENCES t_component_metadata(component_digest)
) STRICT;
CREATE INDEX idx_t_deployment_component_deployment_list
ON t_deployment_component (deployment_id, component_type, component_name);
CREATE INDEX idx_t_deployment_component_deployment_digest
ON t_deployment_component (deployment_id, component_digest);
CREATE INDEX idx_t_state_lock_pending_auto
ON t_state (pending_expires_finished, ffqn, incompatible_digest)
WHERE state = 'pending_at';
CREATE INDEX idx_t_log_execution_id_id
    ON t_log (execution_id, id);
CREATE TABLE t_file (
    digest  TEXT    NOT NULL PRIMARY KEY,
    content BLOB    NOT NULL,
    size    INTEGER NOT NULL
) STRICT;
CREATE TRIGGER t_execution_log_bounded_text_insert
BEFORE INSERT ON t_execution_log
BEGIN
    SELECT RAISE(ABORT, 't_execution_log.variant exceeds 32 characters')
    WHERE length(NEW.variant) > 32;
    SELECT RAISE(ABORT, 't_execution_log.history_event_type exceeds 20 characters')
    WHERE length(NEW.json_value->>'$.history_event.event.type') > 20;
END;
CREATE TRIGGER t_execution_log_bounded_text_update
BEFORE UPDATE OF variant, json_value ON t_execution_log
BEGIN
    SELECT RAISE(ABORT, 't_execution_log.variant exceeds 32 characters')
    WHERE length(NEW.variant) > 32;
    SELECT RAISE(ABORT, 't_execution_log.history_event_type exceeds 20 characters')
    WHERE length(NEW.json_value->>'$.history_event.event.type') > 20;
END;
CREATE TRIGGER t_state_bounded_text_insert
BEFORE INSERT ON t_state
BEGIN
    SELECT RAISE(ABORT, 't_state.component_type exceeds 16 characters')
    WHERE length(NEW.component_type) > 16;
    SELECT RAISE(ABORT, 't_state.deployment_id exceeds 30 characters')
    WHERE length(NEW.deployment_id) > 30;
    SELECT RAISE(ABORT, 't_state.state exceeds 20 characters')
    WHERE length(NEW.state) > 20;
    SELECT RAISE(ABORT, 't_state.executor_id exceeds 30 characters')
    WHERE length(NEW.executor_id) > 30;
    SELECT RAISE(ABORT, 't_state.run_id exceeds 30 characters')
    WHERE length(NEW.run_id) > 30;
END;
CREATE TRIGGER t_state_bounded_text_update
BEFORE UPDATE OF component_type, deployment_id, state, executor_id, run_id ON t_state
BEGIN
    SELECT RAISE(ABORT, 't_state.component_type exceeds 16 characters')
    WHERE length(NEW.component_type) > 16;
    SELECT RAISE(ABORT, 't_state.deployment_id exceeds 30 characters')
    WHERE length(NEW.deployment_id) > 30;
    SELECT RAISE(ABORT, 't_state.state exceeds 20 characters')
    WHERE length(NEW.state) > 20;
    SELECT RAISE(ABORT, 't_state.executor_id exceeds 30 characters')
    WHERE length(NEW.executor_id) > 30;
    SELECT RAISE(ABORT, 't_state.run_id exceeds 30 characters')
    WHERE length(NEW.run_id) > 30;
END;
CREATE TRIGGER t_log_bounded_text_insert
BEFORE INSERT ON t_log
BEGIN
    SELECT RAISE(ABORT, 't_log.run_id exceeds 30 characters')
    WHERE length(NEW.run_id) > 30;
END;
CREATE TRIGGER t_log_bounded_text_update
BEFORE UPDATE OF run_id ON t_log
BEGIN
    SELECT RAISE(ABORT, 't_log.run_id exceeds 30 characters')
    WHERE length(NEW.run_id) > 30;
END;
CREATE TRIGGER t_deployment_bounded_text_insert
BEFORE INSERT ON t_deployment
BEGIN
    SELECT RAISE(ABORT, 't_deployment.deployment_id exceeds 30 characters')
    WHERE length(NEW.deployment_id) > 30;
    SELECT RAISE(ABORT, 't_deployment.status exceeds 8 characters')
    WHERE length(NEW.status) > 8;
    SELECT RAISE(ABORT, 't_deployment.description exceeds 1024 characters')
    WHERE length(NEW.description) > 1024;
    SELECT RAISE(ABORT, 't_deployment.digest exceeds 71 characters')
    WHERE length(NEW.digest) > 71;
END;
CREATE TRIGGER t_deployment_bounded_text_update
BEFORE UPDATE OF deployment_id, status, description, digest ON t_deployment
BEGIN
    SELECT RAISE(ABORT, 't_deployment.deployment_id exceeds 30 characters')
    WHERE length(NEW.deployment_id) > 30;
    SELECT RAISE(ABORT, 't_deployment.status exceeds 8 characters')
    WHERE length(NEW.status) > 8;
    SELECT RAISE(ABORT, 't_deployment.description exceeds 1024 characters')
    WHERE length(NEW.description) > 1024;
    SELECT RAISE(ABORT, 't_deployment.digest exceeds 71 characters')
    WHERE length(NEW.digest) > 71;
END;
CREATE TRIGGER t_deployment_component_bounded_text_insert
BEFORE INSERT ON t_deployment_component
BEGIN
    SELECT RAISE(ABORT, 't_deployment_component.deployment_id exceeds 30 characters')
    WHERE length(NEW.deployment_id) > 30;
    SELECT RAISE(ABORT, 't_deployment_component.component_type exceeds 16 characters')
    WHERE length(NEW.component_type) > 16;
END;
CREATE TRIGGER t_deployment_component_bounded_text_update
BEFORE UPDATE OF deployment_id, component_type ON t_deployment_component
BEGIN
    SELECT RAISE(ABORT, 't_deployment_component.deployment_id exceeds 30 characters')
    WHERE length(NEW.deployment_id) > 30;
    SELECT RAISE(ABORT, 't_deployment_component.component_type exceeds 16 characters')
    WHERE length(NEW.component_type) > 16;
END;
CREATE TRIGGER t_file_bounded_text_insert
BEFORE INSERT ON t_file
BEGIN
    SELECT RAISE(ABORT, 't_file.digest exceeds 71 characters')
    WHERE length(NEW.digest) > 71;
END;
CREATE TRIGGER t_file_bounded_text_update
BEFORE UPDATE OF digest ON t_file
BEGIN
    SELECT RAISE(ABORT, 't_file.digest exceeds 71 characters')
    WHERE length(NEW.digest) > 71;
END;
CREATE TABLE t_component_source (
    component_digest BLOB    NOT NULL,
    frame_key        TEXT    NOT NULL,
    is_suffix        INTEGER NOT NULL,
    digest           TEXT    NOT NULL,

    PRIMARY KEY (component_digest, frame_key, is_suffix),
    FOREIGN KEY (digest) REFERENCES t_file(digest)
) STRICT;
CREATE TRIGGER t_component_source_bounded_text_insert
BEFORE INSERT ON t_component_source
BEGIN
    SELECT RAISE(ABORT, 't_component_source.digest exceeds 71 characters')
    WHERE length(NEW.digest) > 71;
END;
CREATE TRIGGER t_component_source_bounded_text_update
BEFORE UPDATE OF digest ON t_component_source
BEGIN
    SELECT RAISE(ABORT, 't_component_source.digest exceeds 71 characters')
    WHERE length(NEW.digest) > 71;
END;
CREATE INDEX idx_t_state_deployment_state
    ON t_state (deployment_id, is_top_level, state, lifecycle, pending_expires_finished, result_kind);
CREATE UNIQUE INDEX idx_t_join_set_response_execution_id_seq
    ON t_join_set_response (execution_id, seq);
CREATE INDEX idx_t_delay_expires_at
    ON t_delay (expires_at) WHERE NOT is_paused;
CREATE TABLE t_deployment_file (
    deployment_id TEXT NOT NULL,
    path          TEXT NOT NULL,
    digest        TEXT NOT NULL,
    PRIMARY KEY (deployment_id, path),
    FOREIGN KEY (deployment_id) REFERENCES t_deployment(deployment_id)
) STRICT;
CREATE INDEX idx_t_deployment_file_digest ON t_deployment_file (digest);
CREATE TRIGGER t_deployment_file_bounded_text_insert
BEFORE INSERT ON t_deployment_file
BEGIN
    SELECT RAISE(ABORT, 't_deployment_file.deployment_id exceeds 30 characters')
    WHERE length(NEW.deployment_id) > 30;
    SELECT RAISE(ABORT, 't_deployment_file.digest exceeds 71 characters')
    WHERE length(NEW.digest) > 71;
END;
CREATE TRIGGER t_deployment_file_bounded_text_update
BEFORE UPDATE OF deployment_id, digest ON t_deployment_file
BEGIN
    SELECT RAISE(ABORT, 't_deployment_file.deployment_id exceeds 30 characters')
    WHERE length(NEW.deployment_id) > 30;
    SELECT RAISE(ABORT, 't_deployment_file.digest exceeds 71 characters')
    WHERE length(NEW.digest) > 71;
END;
CREATE TABLE t_deployment_component_file (
    deployment_id  TEXT NOT NULL,
    component_name TEXT NOT NULL,
    path           TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'wasm_component' CHECK (role IN (
    'wasm_component', 'exec_program', 'js_entrypoint', 'js_module', 'backtrace_source', 'wit_source'
)),
    PRIMARY KEY (deployment_id, component_name, path),
    FOREIGN KEY (deployment_id, component_name)
        REFERENCES t_deployment_component(deployment_id, component_name),
    FOREIGN KEY (deployment_id, path)
        REFERENCES t_deployment_file(deployment_id, path)
) STRICT;
CREATE INDEX idx_t_deployment_component_file_path
ON t_deployment_component_file (deployment_id, path);
CREATE TRIGGER t_deployment_component_file_bounded_text_insert
BEFORE INSERT ON t_deployment_component_file
BEGIN
    SELECT RAISE(ABORT, 't_deployment_component_file.deployment_id exceeds 30 characters')
    WHERE length(NEW.deployment_id) > 30;
    SELECT RAISE(ABORT, 't_deployment_component_file.role exceeds 16 characters')
    WHERE length(NEW.role) > 16;
END;
CREATE INDEX idx_t_state_tombstoned_roots
    ON t_state (execution_id)
    WHERE is_top_level = TRUE AND tombstoned = TRUE;
CREATE INDEX idx_t_execution_backtrace_backtrace_hash
    ON t_execution_backtrace (backtrace_hash);
CREATE INDEX idx_t_deployment_component_component_digest
    ON t_deployment_component (component_digest);
CREATE INDEX idx_t_deployment_inactive_at
    ON t_deployment (inactive_at, deployment_id)
    WHERE status = 'inactive';
CREATE INDEX idx_t_state_retention_updated_at
    ON t_state (updated_at, execution_id)
    WHERE is_top_level = TRUE AND tombstoned = FALSE;
CREATE TABLE t_system_event (
    event_id TEXT PRIMARY KEY NOT NULL CHECK (length(event_id) <= 64),
    created_at TEXT NOT NULL,
    code TEXT NOT NULL CHECK (length(code) <= 64),
    execution_id TEXT CHECK (length(execution_id) <= 1024),
    deployment_id TEXT CHECK (length(deployment_id) <= 64),
    dedupe_key TEXT CHECK (length(dedupe_key) <= 512),
    cas_digest TEXT REFERENCES t_file(digest) CHECK (length(cas_digest) = 71),
    details TEXT NOT NULL CHECK (length(details) <= 4096)
, level TEXT NOT NULL DEFAULT 'info'
    CHECK (level IN ('debug', 'info', 'warning', 'error')), node_run_id TEXT NOT NULL DEFAULT 'NodeRun_00000000000000000000000000'
    CHECK (length(node_run_id) = 34), app_config_digest TEXT) STRICT;
CREATE INDEX t_system_event_created_idx ON t_system_event(created_at DESC, event_id DESC);
CREATE INDEX t_system_event_code_idx ON t_system_event(code, created_at DESC, event_id DESC);
CREATE INDEX t_system_event_deployment_idx ON t_system_event(deployment_id, created_at DESC, event_id DESC);
CREATE UNIQUE INDEX t_system_event_dedupe_idx
    ON t_system_event(code, deployment_id, dedupe_key)
    WHERE dedupe_key IS NOT NULL;
CREATE INDEX t_system_event_node_run_idx ON t_system_event(node_run_id, event_id DESC);
