package testing:process-obelisk-ext;

interface process {
  use obelisk:types/execution@2.0.0.{execution-id, join-set-id, await-next-extension-error, get-extension-error};

  touch-submit: func(join-set-id: borrow<join-set-id>) -> execution-id;

  touch-await-next: func(join-set-id: borrow<join-set-id>) -> result<tuple<execution-id, result<_, string>>, await-next-extension-error>;

  touch-get: func(execution-id: execution-id) -> result<result<_, string>, get-extension-error>;

  stdio-submit: func(join-set-id: borrow<join-set-id>) -> execution-id;

  stdio-await-next: func(join-set-id: borrow<join-set-id>) -> result<tuple<execution-id, result<_, string>>, await-next-extension-error>;

  stdio-get: func(execution-id: execution-id) -> result<result<_, string>, get-extension-error>;

  kill-submit: func(join-set-id: borrow<join-set-id>) -> execution-id;

  kill-await-next: func(join-set-id: borrow<join-set-id>) -> result<tuple<execution-id, result<_, string>>, await-next-extension-error>;

  kill-get: func(execution-id: execution-id) -> result<result<_, string>, get-extension-error>;

  exec-sleep-submit: func(join-set-id: borrow<join-set-id>) -> execution-id;

  exec-sleep-await-next: func(join-set-id: borrow<join-set-id>) -> result<tuple<execution-id, result<u32, string>>, await-next-extension-error>;

  exec-sleep-get: func(execution-id: execution-id) -> result<result<u32, string>, get-extension-error>;

  subscribe-wait-submit: func(join-set-id: borrow<join-set-id>) -> execution-id;

  subscribe-wait-await-next: func(join-set-id: borrow<join-set-id>) -> result<tuple<execution-id, result<_, string>>, await-next-extension-error>;

  subscribe-wait-get: func(execution-id: execution-id) -> result<result<_, string>, get-extension-error>;
}

