package testing:serde-obelisk-schedule;

interface serde {
  use obelisk:types/execution@2.0.0.{execution-id};
  use obelisk:types/time@2.0.0.{schedule-at};
  use testing:serde/serde.{my-record, my-variant};

  rec-schedule: func(schedule-at: schedule-at, my-record: my-record) -> execution-id;

  var-schedule: func(schedule-at: schedule-at, my-variant: my-variant) -> execution-id;
}

