package testing:fibo-obelisk-ext;

interface fibo {
    use obelisk:types/execution.{execution-id, join-set-id, execution-error};

    fibo-submit: func(join-set-id: join-set-id, n: u8) -> execution-id;

    fibo-await-next: func(join-set-id: join-set-id) -> result<tuple<execution-id, u64>, tuple<execution-id, execution-error>>;
}
