name: check-run-cargo-install

on:
  push:
    branches:
      - main
      - latest

defaults:
  run:
    shell: bash -xe {0}

jobs:
  check-run-cargo-install:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install wget gcc protobuf-compiler libprotobuf-dev -y

      - name: Install obelisk from current path
        run: |
          source "$HOME/.cargo/env"
          cargo install --path . --locked

      - name: Create temp directory
        run: mkdir temp

      - name: Run the binary
        working-directory: temp
        run: |
          source "$HOME/.cargo/env"
          obelisk -v
          obelisk server generate-config
          obelisk server verify
