name: check-run-nix

on:
  workflow_run:
    workflows:
      - check-test
    types:
      - completed

defaults:
  run:
    shell: bash -xe {0}

jobs:
  nix-run:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: "access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}"
      - name: Build and run the binary
        run: nix run .#obeliskNixDev -- --help
