name: check-run

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash -xe {0}

jobs:
  nix-run:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-24.04
            target: .#obeliskGlibcGenericDev
          - runner: ubuntu-24.04
            target: .#obeliskGlibcNixDev
          - runner: ubuntu-22.04
            target: .#obeliskMuslDev

    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: "access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}"

      - name: Create temp directory
        run: mkdir temp

      - name: Build the binary
        working-directory: temp
        run: nix build ${{ matrix.target }}

      - name: Run the binary
        working-directory: temp
        run: |
          ./result/bin/obelisk -v
          ./result/bin/obelisk server generate-config
          ./result/bin/obelisk server verify
