name: check-test
permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - latest
  pull_request:

# If new code is pushed to a PR branch, then cancel in progress workflows for that PR.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -xe {0}

jobs:
  ci-test:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - report: junit-default.xml
            script: "scripts/test.sh"
          - report: junit-js-local.xml
            script: "scripts/test-js-local.sh"

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - uses: nixbuild/nix-quick-install-action@2c9db80fb984ceb1bcaa77cdda3fdf8cfba92035
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Start postgres
        run: docker run -d -e POSTGRES_PASSWORD=postgres -p 5432:5432 postgres:18

      - name: Populate the nix store
        run: nix develop --command echo

      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          cache-on-failure: true
          key: ${{ matrix.report }}

      - name: Build tests
        run: nix develop --command cargo nextest run --workspace --no-run

      - name: Run tests
        run: nix develop --command ${{ matrix.script }}
        env:
          CI: true
          TEST_POSTGRES_HOST: "localhost"
          TEST_POSTGRES_USER: "postgres"
          TEST_POSTGRES_PASSWORD: "postgres"
          TEST_POSTGRES_DATABASE_PREFIX: "obelisk_test"

      # Report results
      - name: Rename test report
        if: always()
        run: mv target/nextest/ci-test/junit.xml target/nextest/ci-test/${{ matrix.report }}
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: ${{ matrix.report }}
          path: target/nextest/ci-test/${{ matrix.report }}
      - name: Report results in GitHub UI
        uses: dorny/test-reporter@a43b3a5f7366b97d083190328d2c652e1a8b6aa2
        if: always()
        with:
          name: Rust tests
          path: target/nextest/ci-test/${{ matrix.report }}
          reporter: java-junit
