name: check-schemas

on:
  push:
    branches:
      - main
      - latest
  pull_request:

# If new code is pushed to a PR branch, then cancel in progress workflows for that PR.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true


defaults:
  run:
    shell: bash -xe {0}

jobs:
  check-build-verify-schema:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31.11.1
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Populate the nix store
        run: nix develop --command echo

      - name: Run `update-schemas.sh`
        run: |
          nix develop --command scripts/update-schemas.sh
          if [ -n "$(git status --porcelain assets/schemas/)" ]; then
            echo "::error::Uncommitted changes after running 'update-schemas.sh'"
            exit 1
          fi
