name: check-extensions

on:
  push:
    branches:
      - main
      - latest
  pull_request:

# If new code is pushed to a PR branch, then cancel in progress workflows for that PR.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -xe {0}

jobs:
  check-extensions:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

      - uses: nixbuild/nix-quick-install-action@9f63be77f412a248c9d9a65a4c82cf066cdf8f0c
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Populate the nix store
        run: nix develop --command echo

      - name: Run `scripts/regenerate-wit-extensions.sh`
        run: |
          nix develop --command scripts/regenerate-wit-extensions.sh
          if [ -n "$(git status --porcelain)" ]; then
            echo "::error::Uncommitted changes after running 'regenerate-wit-extensions.sh'"
            exit 1
          fi
