name: check-run-cargo-install

# Run cargo install --path . on each push to main or latest, using
# the default devshell in order to match the `rust-toolchain.toml` file.

on:
  push:
    branches:
      - main
      - latest

defaults:
  run:
    shell: bash -xe {0}

jobs:
  check-run-cargo-install:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: nixbuild/nix-quick-install-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Populate the nix store
        run: nix develop --command echo

      - name: Install obelisk from current path
        run: nix develop --command cargo install --path . --locked --debug

      - name: Create temp directory
        run: mkdir temp

      - name: Run the binary
        working-directory: temp
        run: |
          $HOME/.cargo/bin/obelisk -v
          # $HOME/.cargo/bin/obelisk server generate-config # does not work for debug builds
          cp ../obelisk.toml .
          $HOME/.cargo/bin/obelisk server verify
