name: CodSpeed

on:
  workflow_dispatch:

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1

      - uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31.11.1
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Populate the nix store
        run: nix develop --command echo

      - name: Build the benchmark target(s)
        run: nix develop --command cargo codspeed build -p bench --jobs 1

      - name: Run benchmarks
        uses: CodSpeedHQ/action@v5
        with:
          token: ${{ secrets.CODSPEED_TOKEN }}
          run: nix develop --command cargo codspeed run -p bench
        env:
          RUST_BACKTRACE: 1
