name: release-artifacts

permissions:
  contents: write

on:
  workflow_dispatch:

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTUP_MAX_RETRIES: 10

defaults:
  run:
    shell: bash

jobs:
  upload-assets:
    name: ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-22.04
            nix_target: obelisk-patch-for-generic-linux
          - target: x86_64-unknown-linux-musl
            os: ubuntu-22.04
            nix_target: obeliskMusl
    steps:
      - uses: actions/checkout@v4
      - id: git-info
        run: |
          echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          echo "branch=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_OUTPUT
          echo "tag=$(git tag --contains HEAD)" >> $GITHUB_OUTPUT

      - id: release-info
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/obeli-sk/obelisk/releases/tags/${{ steps.git-info.outputs.tag }} > release.json
          RELEASE_ID=$(cat release.json | grep -oP '^  "id":\s\K\d+')
          echo "release_id=$RELEASE_ID" >> $GITHUB_OUTPUT

      - name: Install Nix
        uses: cachix/install-nix-action@V27
        with:
          extra_nix_config: "access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}"

      - name: Build obelisk
        run: nix build '.#${{ matrix.nix_target }}'

      - name: Create a tar.gz archive
        run: tar czf archive.tar.gz --transform='s/^result\/bin\///' result/bin/obelisk

      - name: Upload the archive
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/octet-stream" \
            --data-binary @archive.tar.gz \
            "https://uploads.github.com/repos/obeli-sk/obelisk/releases/${{ steps.release-info.outputs.release_id }}/assets?name=obelisk-${{ matrix.target }}.tar.gz"
