name: release-3-upload-artifacts-macos

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "The ref (branch or SHA) to process"
        required: false
        type: string
  release:
    types: [released]

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTUP_MAX_RETRIES: 10

defaults:
  run:
    shell: bash -xe {0}

jobs:
  upload-assets:
    name: ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-macos
            os: macos-13
          - target: arm64-macos
            os: macos-13-arm64
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }} # Use the ref if provided, otherwise defaults to the current branch/commit

      - id: git-info
        run: |
          echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          echo "branch=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_OUTPUT
          echo "tag=$(git tag --contains HEAD)" >> $GITHUB_OUTPUT

      - id: release-info
        run: |
          curl --fail -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/obeli-sk/obelisk/releases/tags/${{ steps.git-info.outputs.tag }} > release.json
          RELEASE_ID=$(jq -r '.id' release.json)
          echo "release_id=$RELEASE_ID" >> $GITHUB_OUTPUT

      - name: Install rustc
        run: brew install rust

      - name: Install protobuf
        run: brew install protobuf

      - name: Build obelisk
        run: cargo build --release

      - name: Create a tar.gz archive
        run: tar czf archive.tar.gz --transform='s/^target\/release\///' target/release/obelisk

      - name: Upload the archive
        run: |
          curl -v --fail -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/octet-stream" \
            --data-binary @archive.tar.gz \
            "https://uploads.github.com/repos/obeli-sk/obelisk/releases/${{ steps.release-info.outputs.release_id }}/assets?name=obelisk-${{ matrix.target }}.tar.gz"
