name: release-5-verify-docker

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "The ref (branch or SHA) to obtain the tag"
        required: false
        type: string
        default: "latest"
  workflow_call:
    inputs:
      ref:
        description: "The ref (branch or SHA) to obtain the tag"
        required: false
        type: string
        default: "latest"

defaults:
  run:
    shell: bash -xe {0}

jobs:
  verify-docker-image:
    name: verify-${{ matrix.image_tag }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - image_tag: ubuntu
          - image_tag: alpine
          - image_tag: ubuntu-litestream
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          ref: ${{ inputs.ref }}

      - id: git-info
        run: |
          VERSION="$(grep -m1 '^version = "' Cargo.toml | cut -d'"' -f2)"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag=v$VERSION" >> $GITHUB_OUTPUT
          echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Verify docker image
        run: |
          IMAGE="getobelisk/obelisk:${VERSION}-${{ matrix.image_tag }}"
          echo "Pulling $IMAGE"
          docker pull $IMAGE
          docker run --rm $IMAGE --version | grep $VERSION
          docker run --rm -v $PWD/obelisk-testing-wasm-oci.toml:/etc/obelisk/deployment.toml $IMAGE server verify --deployment /etc/obelisk/deployment.toml
        env:
          VERSION: ${{ steps.git-info.outputs.version }}
