name: release-artifacts

permissions:
  contents: write

on:
  workflow_dispatch:
  release:
    types: [released]

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTUP_MAX_RETRIES: 10

defaults:
  run:
    shell: bash

jobs:
  upload-assets:
    name: ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-22.04
            nix_target: obelisk
          - target: x86_64-unknown-linux-musl
            os: ubuntu-22.04
            nix_target: obeliskMusl
    steps:
      - uses: actions/checkout@v4
      - id: git-info
        run: |
          echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          echo "branch=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_OUTPUT
      - name: Install Nix
        uses: cachix/install-nix-action@V27
        with:
          extra_nix_config: "access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}"

      - name: Build obelisk
        run: nix build '.#${{ matrix.nix_target }}'
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: result/bin/obelisk
          target: ${{ matrix.target }}
          tar: all
          zip: windows
          token: ${{ secrets.GITHUB_TOKEN }}
