name: release-5-verify-install-sh

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "The ref (branch or SHA) to obtain the tag"
        required: false
        type: string
  workflow_run:
    workflows:
      - release-3-upload-artifacts
    types:
      - completed

defaults:
  run:
    shell: bash -xe {0}

jobs:
  verify-assets:
    name: ${{ matrix.runner }}
    runs-on: ${{ matrix.runner }}
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-22.04
          - runner: macos-13
          - runner: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }} # Use the ref if provided, otherwise defaults to the current branch/commit

      - id: git-info
        run: |
          git fetch --tags
          echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          echo "branch=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_OUTPUT
          echo "tag=$(git tag --contains HEAD)" >> $GITHUB_OUTPUT

      - run: |
          TAG="${{ steps.git-info.outputs.tag }}"
          if [ -z "$TAG" ]; then
            echo "No tag pointing at HEAD."
            exit 1
          fi
          VERSION=${TAG#v}
          mkdir temp
          cd temp
          curl -L --tlsv1.2 -sSf https://raw.githubusercontent.com/obeli-sk/obelisk/main/install.sh | bash
          ./obelisk --version | grep $VERSION
          ./obelisk server generate-config
          ./obelisk server verify
