name: release-5-push-docker-image

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash -xe {0}

jobs:
  push-image:
    name: ${{ matrix.dockerfile }}
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - tarfile: obelisk-x86_64-unknown-linux-gnu.tar.gz
            dockerfile: ubuntu-24.04.Dockerfile
            docker_image: getobelisk/obelisk
          - tarfile: obelisk-x86_64-unknown-linux-musl.tar.gz
            dockerfile: alpine.Dockerfile
            docker_image: getobelisk/obelisk:alpine

    steps:
      - uses: actions/checkout@v4
      - run: |
          mkdir tmp
          cd tmp
          wget https://github.com/obeli-sk/obelisk/releases/latest/download/${{ matrix.tarfile }}
          tar xvfz ${{ matrix.tarfile }}
          echo 'api_listening_addr = "0.0.0.0:5005"' > obelisk.toml
          cat ../obelisk.toml >> obelisk.toml
          docker build --progress=plain -f ../.github/workflows/release/docker-image/${{ matrix.dockerfile }} . --tag ${{ matrix.docker_image }}
          docker login -u getobelisk -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push ${{ matrix.docker_image }}
          # Add version
          tags=$(git tag --points-at HEAD)
          if [ $(echo "$tags" | wc -l) -eq 1 ]; then
              if [[ $tags == v* ]]; then
                  version=${tags#v}
                  tagged=${{ matrix.docker_image }}
                  echo "Tagging as ${tagged}"
                  docker tag ${{ matrix.docker_image }} ${tagged}
                  docker push ${tagged}
              fi
          fi
