name: release-4-verify-docker

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - release-3-upload-artifacts
    types:
      - completed

defaults:
  run:
    shell: bash -xe {0}

jobs:
  verify-assets:
    name: ${{ matrix.target }}
    runs-on: ubuntu-24.04
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: alpine-binstall
          - target: ubuntu-24.04-binstall
          - target: ubuntu-24.04-install
    steps:
      - uses: actions/checkout@v4
      - run: |
          cat .github/workflows/release/verify/${{ matrix.target }}.Dockerfile | docker build --progress=plain -
