name: release-3-upload-artifacts

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "The ref (branch or SHA) to process"
        required: false
        type: string
  workflow_run:
    workflows:
      - release-2-plz-release
    types:
      - completed

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTUP_MAX_RETRIES: 10

defaults:
  run:
    shell: bash -xe {0}

jobs:
  upload-assets:
    name: ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-22.04
          - target: x86_64-unknown-linux-musl
            os: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }} # Use the ref if provided, otherwise defaults to the current branch/commit

      - id: git-info
        run: |
          git fetch --tags
          echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          echo "branch=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_OUTPUT
          echo "tag=$(git tag --contains HEAD)" >> $GITHUB_OUTPUT

      - id: release-info
        run: |
          curl --fail -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/obeli-sk/obelisk/releases/tags/${{ steps.git-info.outputs.tag }} > release.json
          RELEASE_ID=$(jq -r '.id' release.json)
          echo "release_id=$RELEASE_ID" >> $GITHUB_OUTPUT

      # Build the musl binary with Nix
      - name: Install Nix
        if: ${{ matrix.target == 'x86_64-unknown-linux-musl' }}
        uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: "access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}"
      - name: Build obelisk with Nix
        if: ${{ matrix.target == 'x86_64-unknown-linux-musl' }}
        run: nix build '.#obeliskMusl'
      - name: Create a tar.gz archive
        if: ${{ matrix.target == 'x86_64-unknown-linux-musl' }}
        run: tar czf archive.tar.gz --transform='s/^result\/bin\///' result/bin/obelisk

      # Build the glibc binary natively
      - name: Install Rust
        if: ${{ matrix.target == ' x86_64-unknown-linux-gnu' }}
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - name: Install dependencies
        if: ${{ matrix.target == ' x86_64-unknown-linux-gnu' }}
        run: |
          sudo apt update
          sudo apt install wget gcc protobuf-compiler libprotobuf-dev -y
      - name: Install obelisk from crates.io
        if: ${{ matrix.target == ' x86_64-unknown-linux-gnu' }}
        run: |
          source "$HOME/.cargo/env"
          TAG=${{ steps.git-info.outputs.tag }}
          TAG=${TAG#v}
          cargo install obelisk@$TAG --locked --root .
          tar czf archive.tar.gz --transform='s/^target\/release\///' target/release/obelisk

      - name: Upload the archive
        run: |
          curl -v --fail -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/octet-stream" \
            --data-binary @archive.tar.gz \
            "https://uploads.github.com/repos/obeli-sk/obelisk/releases/${{ steps.release-info.outputs.release_id }}/assets?name=obelisk-${{ matrix.target }}.tar.gz"
