name: release-2-plz-release

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "The ref (branch or SHA) to process"
        required: false
        type: string
      latest:
        description: "Should the branch `latest` be updated?"
        required: false
        type: boolean
        default: true

defaults:
  run:
    shell: bash -xe {0}

jobs:
  release-plz-release:
    name: Release-plz-release
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }} # Use the ref if provided, otherwise defaults to the current branch/commit
          fetch-depth: 0

      - uses: nixbuild/nix-quick-install-action@v29
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure git before push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run release-plz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_TOKEN }}
        run: |
          nix develop --command release-plz release --backend github --git-token $GITHUB_TOKEN

      - name: Update `latest` branch
        if: ${{ github.event.inputs.latest }}
        run: |
          git push --force origin HEAD:latest
