name: release-3-upload-artifacts

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "The ref (branch or SHA) to process"
        required: false
        type: string
  workflow_run:
    workflows:
      - release-2-cargo-publish
    types:
      - completed

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTUP_MAX_RETRIES: 10

defaults:
  run:
    shell: bash -xe {0}

jobs:
  create-github-release:
    runs-on: ubuntu-24.04
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }} # Use the ref if provided, otherwise defaults to the current branch/commit

      - name: Create GitHub Release
        run: |
          TAG=$(grep -m1 '^version = "' Cargo.toml | cut -d'"' -f2)
          SHA=$(git rev-parse HEAD)
          echo "Releasing $TAG $SHA"
          curl -v --fail -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -d '{
              "tag_name": "'$TAG'",
              "target_commitish": "'$SHA'",
              "name": "obelisk-'$TAG'",
              "body": "",
              "draft": false,
              "prerelease": false
            }' \
            https://api.github.com/repos/obeli-sk/obelisk/releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    name: ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    needs: create-github-release
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-22.04 # Make sure to use the old libc for native build.
          - target: x86_64-unknown-linux-musl
            os: ubuntu-24.04 # Does not matter as musl is built with Nix.
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-22.04-arm # Make sure to use the old libc for native build.
          - target: aarch64-unknown-linux-musl
            os: ubuntu-22.04-arm # Does not matter as musl is built with Nix.
          - target: x86_64-apple-darwin
            os: macos-13
          - target: aarch64-apple-darwin
            os: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }} # Use the ref if provided, otherwise defaults to the current branch/commit

      - id: git-info
        run: |
          git fetch --tags
          echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          echo "branch=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_OUTPUT
          echo "tag=$(git tag --contains HEAD)" >> $GITHUB_OUTPUT

      - id: release-info
        run: |
          curl --fail -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/obeli-sk/obelisk/releases/tags/${{ steps.git-info.outputs.tag }} > release.json
          RELEASE_ID=$(jq -r '.id' release.json)
          echo "release_id=$RELEASE_ID" >> $GITHUB_OUTPUT

      # Build the musl binary with Nix
      - name: Install Nix
        if: ${{ endsWith(matrix.target, '-musl') }}
        uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            extra-substituters = https://cache.garnix.io                                                         │
            extra-trusted-public-keys = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g
      - name: Build Obelisk with Nix
        if: ${{ endsWith(matrix.target, '-musl') }}
        run: nix build '.#obeliskMusl'
      - name: Create a tar.gz archive
        if: ${{ endsWith(matrix.target, '-musl') }}
        run: tar czf archive.tar.gz --transform='s/^result\/bin\///' result/bin/obelisk

      # Build natively for !musl
      - name: Install Rust
        if: ${{ !endsWith(matrix.target, '-musl') }}
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - name: Install dependencies - Ubuntu GNU libc
        if: ${{ endsWith(matrix.target, '-gnu') }}
        run: |
          sudo apt update
          sudo apt install wget gcc protobuf-compiler libprotobuf-dev -y
      - name: Install dependencies - MacOS
        if: startsWith(matrix.os, 'macos-')
        run: |
          brew install protobuf
          brew install gnu-tar
      - name: Install Obelisk from crates.io - macos and linux-gnu = all non-musl targets
        if: ${{ !endsWith(matrix.target, '-musl') }}
        run: |
          source "$HOME/.cargo/env"
          TAG=${{ steps.git-info.outputs.tag }}
          if [ -z "$TAG" ]; then
            echo "No tag pointing at HEAD."
            exit 1
          fi
          TAG=${TAG#v}
          cargo install obelisk@$TAG --locked --root .
          TAR_CMD=$(if [[ $RUNNER_OS == 'macOS' ]]; then echo gtar; else echo tar; fi)
          $TAR_CMD czf archive.tar.gz --transform='s/^bin\///' bin/obelisk

      # Common for all targets
      - name: Upload the archive
        run: |
          curl -v --fail -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/octet-stream" \
            --data-binary @archive.tar.gz \
            "https://uploads.github.com/repos/obeli-sk/obelisk/releases/${{ steps.release-info.outputs.release_id }}/assets?name=obelisk-${{ matrix.target }}.tar.gz"
