name: release-2-plz-release

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "The ref (branch or SHA) to process"
        required: false
        type: string
      latest:
        description: "Should the branch `latest` be updated?"
        required: false
        type: boolean
        default: true

defaults:
  run:
    shell: bash -xe {0}

jobs:
  release-plz-release:
    name: Release-plz-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }} # Use the ref if provided, otherwise defaults to the current branch/commit
          fetch-depth: 0

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install protobuf
        run: |
          sudo apt update
          sudo apt install -y protobuf-compiler libprotobuf-dev
      - name: Run release-plz
        uses: MarcoIeni/release-plz-action@v0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_TOKEN }}
        with:
          command: release

      - name: Update `latest` branch
        if: ${{ github.event.inputs.latest }}
        run: |
          git push --force origin HEAD:latest
