name: release-5-push-docker-image

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'The ref (branch or SHA) to process'
        required: false
        type: string

defaults:
  run:
    shell: bash -xe {0}

jobs:
  push-image:
    name: ${{ matrix.dockerfile }}
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - tarfile: obelisk-x86_64-unknown-linux-gnu.tar.gz
            dockerfile: ubuntu-24.04.Dockerfile
            image_tag: ubuntu
            latest: true
          - tarfile: obelisk-x86_64-unknown-linux-musl.tar.gz
            dockerfile: alpine.Dockerfile
            image_tag: alpine
            latest: false

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}  # Use the ref if provided, otherwise defaults to the current branch/commit

      - run: |
          docker login -u getobelisk -p ${{ secrets.DOCKER_HUB_TOKEN }}
          mkdir tmp
          cd tmp
          wget -q https://github.com/obeli-sk/obelisk/releases/latest/download/${{ matrix.tarfile }}
          tar xvfz ${{ matrix.tarfile }}
          cp ../obelisk.toml obelisk.toml
          sed -i 's/api_listening_addr.*/api_listening_addr = "0.0.0.0:5005"/g' obelisk.toml
          IMAGE_BASE="getobelisk/obelisk"
          IMAGE="${IMAGE_BASE}:${{ matrix.image_tag }}"
          docker build --progress=plain -f ../.github/workflows/release/docker-image/${{ matrix.dockerfile }} . --tag $IMAGE
          docker push $IMAGE

          TAGS=$(git tag --points-at HEAD)
          TAGS=$(echo "$TAGS" | grep '^v' || true)
          if [ -z "$TAGS" ]; then
            echo "No tags starting with 'v' pointing at HEAD."
            exit 1
          elif [ $(echo "$TAGS" | wc -l) -eq 1 ]; then
            VERSION="${TAGS#v}"
            echo "Tagging with version ${VERSION}"
            IMAGE2="${IMAGE_BASE}:${VERSION}-${{ matrix.image_tag }}"
            echo "Tagging as $IMAGE2"
            docker tag $IMAGE $IMAGE2
            docker push $IMAGE2
          else
            echo "More than one tag starting with 'v' pointing at HEAD."
            exit 1
          fi

          if [ "${{ matrix.latest }}" = "true" ]; then
            docker tag $IMAGE $IMAGE_BASE
            docker push $IMAGE_BASE
          fi
