name: scheduled-audit

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  deny:
    name: cargo deny
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - uses: nixbuild/nix-quick-install-action@9f63be77f412a248c9d9a65a4c82cf066cdf8f0c
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Populate the nix store
        run: nix develop --command echo

      - name: cargo deny
        run: nix develop --command cargo deny check
