name: test
permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

# This configuration allows maintainers of this repo to create a branch and pull request based on
# the new branch. Restricting the push trigger to the main branch ensures that the PR only gets
# built once.
on:
  push:
    branches:
      - main
  pull_request:
# If new code is pushed to a PR branch, then cancel in progress workflows for that PR.

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -xe {0}

jobs:
  ci-test-nosim:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - id: git-info
        run: |
          echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          echo "branch=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_OUTPUT
      - name: Install Nix
        uses: cachix/install-nix-action@V27
        with:
          extra_nix_config: "access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}"
      - name: Populate the nix store
        run: nix develop --command echo
      - name: Build tests
        run: nix develop --command cargo nextest run --workspace --all-features --no-run
      - name: Populate the codegen cache
        run: nix develop --command cargo nextest run --workspace --all-features --profile ci-test-populate-codegen-cache populate_codegen_cache --test-threads 1
        env:
          CI: true
      - name: cargo test
        env:
          RUST_LOG: "info,executor=trace,wasm_workers=trace,db=info"
          CI: true
        run: nix develop --command cargo nextest run --workspace --all-features  --profile ${{ github.job }} --test-threads 1
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: Test results - nosim
          files: |
            target/nextest/${{ github.job }}/junit.xml

  ci-test-madsim:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - id: git-info
        run: |
          echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          echo "branch=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_OUTPUT
      - name: Install Nix
        uses: cachix/install-nix-action@V27
        with:
          extra_nix_config: "access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}"
      - name: Populate the nix store
        run: nix develop --command echo
      - name: Build tests
        env:
          RUSTFLAGS: "--cfg madsim"
        run: nix develop --command cargo nextest run --workspace --no-run
      - name: Populate the codegen cache
        run: nix develop --command cargo nextest run --workspace --all-features --profile ci-test-populate-codegen-cache populate_codegen_cache --test-threads 1
        env:
          RUSTFLAGS: "--cfg madsim"
          CI: true
      - name: cargo test
        env:
          RUSTFLAGS: "--cfg madsim"
          RUST_LOG: "info,executor=trace,wasm_workers=trace,db=info"
          MADSIM_ALLOW_SYSTEM_THREAD: "1"
          CI: true
        run: nix develop --command cargo nextest run --workspace --profile ${{ github.job }} --test-threads 1
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: Test results - madsim
          files: |
            target/nextest/${{ github.job }}/junit.xml
